source 'https://rubygems.org'

require 'json'
require 'open-uri'
versions = JSON.parse(open('https://pages.github.com/versions.json').read)

gem 'asciidoctor'
gem 'pygments.rb'
gem 'just-the-docs'

group :jekyll_plugins do
  gem 'github-pages', versions['github-pages']
  gem 'jekyll', versions['jekyll']
  gem 'jekyll-sitemap', versions['jekyll-sitemap']
  gem 'jekyll-asciidoc', '2.1.1'
  gem 'asciidoctor-diagram'
end
