/*
 * KISS, YAGNI, DRY
 *
 * (c) Copyright 2016, Michal Šipoš
 *
 *  This program is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 2 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License along
 *  with this program; if not, write to the Free Software Foundation, Inc.,
 *  51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 */

package net.sf.emustudio.rasp.memory.gui;

import emulib.plugins.memory.Memory;
import emulib.runtime.StaticDialogs;
import emulib.runtime.UniversalFileFilter;
import net.sf.emustudio.rasp.memory.impl.RASPMemoryContextImpl;

import javax.swing.*;
import java.io.File;
import java.io.IOException;

/**
 * GUI window representing memory.
 *
 * @author miso
 */
public class MemoryWindow extends javax.swing.JFrame {

    private final RASPMemoryContextImpl memory;
    private final RASPTableModel tableModel;
    private File recentOpenPath;

    /**
     * Creates new form MemoryWindow
     *
     * @param context the memory context
     */
    public MemoryWindow(RASPMemoryContextImpl context) {
        this.memory = context;
        this.recentOpenPath = new File(System.getProperty("user.home"));

        initComponents();
        tableModel = new RASPTableModel(memory);
        //memoryTable.setModel(tableModel); - not needed, already set at initComponents()
        updateTable();
        memory.addMemoryListener(new Memory.MemoryListener() {

            @Override
            public void memoryChanged(int position) {
                updateTable();
            }

            @Override
            public void memorySizeChanged() {
                updateTable();
            }
        });
    }

    /**
     * Update the table.
     */
    private void updateTable() {
        tableModel.fireTableDataChanged();
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        memoryTable = new javax.swing.JTable();
        jToolBar1 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("RASP Memory");

        memoryTable.setModel(new RASPTableModel(memory));
        memoryTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                memoryTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(memoryTable);
        if (memoryTable.getColumnModel().getColumnCount() > 0) {
            memoryTable.getColumnModel().getColumn(0).setResizable(false);
            memoryTable.getColumnModel().getColumn(1).setResizable(false);
        }

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/net/sf/emustudio/rasp/memory/gui/document-open.png"))); // NOI18N
        jButton1.setFocusable(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onOpenClick(evt);
            }
        });
        jToolBar1.add(jButton1);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/net/sf/emustudio/rasp/memory/gui/edit-delete.png"))); // NOI18N
        jButton2.setFocusable(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onClearClick(evt);
            }
        });
        jToolBar1.add(jButton2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 491, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void onOpenClick(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onOpenClick
        JFileChooser chooser = new JFileChooser();

        UniversalFileFilter binaryFileFilter = new UniversalFileFilter();
        binaryFileFilter.addExtension("bin");
        binaryFileFilter.setDescription("Compiled program for RASP (*.bin)");

        chooser.setDialogTitle("Load memory with compiled program file");
        chooser.addChoosableFileFilter(binaryFileFilter);
        chooser.setFileFilter(binaryFileFilter);
        chooser.setApproveButtonText("Load");
        chooser.setCurrentDirectory(recentOpenPath);

        int chooserReturnValue = chooser.showOpenDialog(this);
        if (chooserReturnValue == JFileChooser.APPROVE_OPTION) {
            String filePath = chooser.getSelectedFile().getAbsolutePath();
            recentOpenPath = chooser.getCurrentDirectory();
            try {
                memory.loadFromFile(filePath);
                updateTable();
            } catch (IOException | ClassNotFoundException ex) {
                StaticDialogs.showErrorMessage("File " + filePath + " can't be read: " + ex.getMessage());
            }
        }
    }//GEN-LAST:event_onOpenClick

    private void onClearClick(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onClearClick
        memory.clear();
    }//GEN-LAST:event_onClearClick

    /**
     * Called when user double-clicks at a row; editor is displayed at the
     * "Numeric value" column. It is to make UI more user friendly as user does
     * not have to click at an editable cell, he/she just double-clicks the row.
     *
     * @param evt the click event
     */
    private void memoryTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_memoryTableMouseClicked
        int row = memoryTable.rowAtPoint(evt.getPoint());
        //check if double-click
        if (evt.getClickCount() == 2) {
            memoryTable.editCellAt(row, 1);
        }
    }//GEN-LAST:event_memoryTableMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTable memoryTable;
    // End of variables declaration//GEN-END:variables
}
