title: Emulator programming tutorial for emuStudio 0.40
email: emustudio@googlegroups.com
tagline: Emulator programming tutorial for emuStudio 0.40
description: >- # this means to ignore newlines until "baseurl:"
  Emulator programming tutorial for emuStudio 0.40. emuStudio is universal emulation platform
  and framework targeting mainly academic sphere.
baseurl: "/docs/developer/0.40" # the subpath of your site, e.g. /blog
url: ""
github_username:  emustudio
ga_tracking: UA-3492956-5

logo: "/assets/logo-1.svg"
aux_links:
  "Back to website":
    - "//www.emustudio.net"

# Build settings
markdown: kramdown
theme: "just-the-docs"
plugins:
  - jekyll-feed
  - asciidoctor-diagram
  - jekyll-asciidoc
whitelist: [jekyll-asciidoc]

asciidoc:
  processor: asciidoctor

asciidoctor:
  base_dir: :docdir
  safe: unsafe
  attributes:
    imagesdir: /docs/developer/0.40/docs/
    source-highlighter: pygments
    pygments-css: style
    icons: font


destination: ../../../docs/developer/0.40
