/*
 * This file is part of emuStudio.
 *
 * Copyright (C) 2006-2020  Peter Jakubčo
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */
package net.emustudio.plugins.device.mits88sio.gui;

import net.emustudio.emulib.runtime.CannotUpdateSettingException;
import net.emustudio.emulib.runtime.interaction.Dialogs;
import net.emustudio.plugins.device.mits88sio.SIOSettings;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import javax.swing.*;
import java.awt.*;
import java.util.Arrays;
import java.util.Objects;

public class ConfigDialog extends javax.swing.JDialog {
    private final static Logger LOGGER = LoggerFactory.getLogger(ConfigDialog.class);

    private final Dialogs dialogs;

    private final SIOSettings settings;
    private final PortListModel statusPortsModel = new PortListModel();
    private final PortListModel dataPortsModel = new PortListModel();

    public ConfigDialog(SIOSettings settings, Dialogs dialogs) {
        this.settings = Objects.requireNonNull(settings);
        this.dialogs = Objects.requireNonNull(dialogs);

        super.setLocationRelativeTo(null);
        initComponents();

        statusPortsModel.addAll(settings.getStatusPorts());
        dataPortsModel.addAll(settings.getDataPorts());
    }

    private void setDefaultStatusPorts() {
        statusPortsModel.clear();
        statusPortsModel.addAll(Arrays.asList(3, 16, 20, 22, 24));
    }

    private void setDefaultDataPorts() {
        dataPortsModel.clear();
        dataPortsModel.addAll(Arrays.asList(2, 17, 21, 23, 25));
    }


    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JPanel jPanel1 = new javax.swing.JPanel();
        JScrollPane jScrollPane1 = new JScrollPane();
        lstStatusPorts = new javax.swing.JList<>();
        JButton btnStatusAdd = new JButton();
        JButton btnStatusRemove = new JButton();
        JButton btnStatusDefault = new JButton();
        javax.swing.JPanel jPanel2 = new javax.swing.JPanel();
        JScrollPane jScrollPane2 = new JScrollPane();
        lstDataPorts = new javax.swing.JList<>();
        // Variables declaration - do not modify//GEN-BEGIN:variables
        JButton btnDataAdd = new JButton();
        JButton btnDataRemove = new JButton();
        JButton btnDataDefault = new JButton();
        javax.swing.JLabel jLabel1 = new javax.swing.JLabel();
        JCheckBox chkApplyAtStartup = new JCheckBox();
        JButton btnOK = new JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("MITS SIO Settings");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Status port -> CPU"));

        lstStatusPorts.setFont(new java.awt.Font("Monospaced", Font.PLAIN, 12)); // NOI18N
        lstStatusPorts.setModel(statusPortsModel);
        lstStatusPorts.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(lstStatusPorts);

        btnStatusAdd.setFont(btnStatusAdd.getFont().deriveFont(btnStatusAdd.getFont().getStyle() & ~java.awt.Font.BOLD));
        btnStatusAdd.setText("+");
        btnStatusAdd.addActionListener(this::btnStatusAddActionPerformed);

        btnStatusRemove.setFont(btnStatusRemove.getFont().deriveFont(btnStatusRemove.getFont().getStyle() & ~java.awt.Font.BOLD));
        btnStatusRemove.setText("-");
        btnStatusRemove.setToolTipText("");
        btnStatusRemove.addActionListener(this::btnStatusRemoveActionPerformed);

        btnStatusDefault.setFont(btnStatusDefault.getFont().deriveFont(btnStatusDefault.getFont().getStyle() & ~java.awt.Font.BOLD));
        btnStatusDefault.setText("Default");
        btnStatusDefault.addActionListener(this::btnStatusDefaultActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnStatusAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnStatusRemove, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(btnStatusDefault))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(btnStatusAdd)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnStatusRemove)))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(btnStatusDefault)
                    .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Data port -> CPU"));

        lstDataPorts.setFont(new java.awt.Font("Monospaced", Font.PLAIN, 12)); // NOI18N
        lstDataPorts.setModel(dataPortsModel);
        lstDataPorts.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(lstDataPorts);

        btnDataAdd.setFont(btnDataAdd.getFont().deriveFont(btnDataAdd.getFont().getStyle() & ~java.awt.Font.BOLD));
        btnDataAdd.setText("+");
        btnDataAdd.addActionListener(this::btnDataAddActionPerformed);

        btnDataRemove.setFont(btnDataRemove.getFont().deriveFont(btnDataRemove.getFont().getStyle() & ~java.awt.Font.BOLD));
        btnDataRemove.setText("-");
        btnDataRemove.setToolTipText("");
        btnDataRemove.addActionListener(this::btnDataRemoveActionPerformed);

        btnDataDefault.setFont(btnDataDefault.getFont().deriveFont(btnDataDefault.getFont().getStyle() & ~java.awt.Font.BOLD));
        btnDataDefault.setText("Default");
        btnDataDefault.addActionListener(this::btnDataDefaultActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnDataAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnDataRemove, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(btnDataDefault))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(btnDataAdd)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnDataRemove)))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(btnDataDefault)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setFont(jLabel1.getFont().deriveFont(jLabel1.getFont().getStyle() & ~java.awt.Font.BOLD));
        jLabel1.setText("<html>It is possible to bind status port of this device to one or more CPU ports. Please be aware of not interferencing with other devices.");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        chkApplyAtStartup.setFont(chkApplyAtStartup.getFont().deriveFont(chkApplyAtStartup.getFont().getStyle() & ~java.awt.Font.BOLD));
        chkApplyAtStartup.setSelected(true);
        chkApplyAtStartup.setText("Apply at startup");

        btnOK.setText("OK");
        btnOK.addActionListener(this::btnOKActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(chkApplyAtStartup)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnOK, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(chkApplyAtStartup)
                        .addComponent(btnOK))
                    .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnStatusAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStatusAddActionPerformed
        try {
            dialogs
                .readInteger("Enter port number:", "Add status port", 0)
                .ifPresent(port -> {
                    if (dataPortsModel.contains(port)) {
                        dialogs.showError("Port number is already taken by data port", "Add status port");
                    } else {
                        statusPortsModel.add(port);
                    }

                });
        } catch (NumberFormatException e) {
            dialogs.showError("Invalid number format", "Add status port");
        }
    }//GEN-LAST:event_btnStatusAddActionPerformed

    private void btnDataAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDataAddActionPerformed
        try {
            dialogs
                .readInteger("Enter port number:", "Add data port", 0)
                .ifPresent(port -> {
                    if (statusPortsModel.contains(port)) {
                        dialogs.showError("Port number is already taken by status port");
                    } else {
                        dataPortsModel.add(port);
                    }
                });
        } catch (NumberFormatException e) {
            dialogs.showError("Invalid number format", "Add data port");
        }
    }//GEN-LAST:event_btnDataAddActionPerformed

    private void btnStatusRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStatusRemoveActionPerformed
        int i = lstStatusPorts.getSelectedIndex();
        if (i == -1) {
            dialogs.showError("Status port must be selected", "Remove status port");
        } else {
            statusPortsModel.removeAt(i);
        }
    }//GEN-LAST:event_btnStatusRemoveActionPerformed

    private void btnDataRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDataRemoveActionPerformed
        int i = lstDataPorts.getSelectedIndex();
        if (i == -1) {
            dialogs.showError("Data port must be selected", "Remove data port");
        } else {
            dataPortsModel.removeAt(i);
        }
    }//GEN-LAST:event_btnDataRemoveActionPerformed

    private void btnDataDefaultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDataDefaultActionPerformed
        setDefaultDataPorts();
    }//GEN-LAST:event_btnDataDefaultActionPerformed

    private void btnStatusDefaultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStatusDefaultActionPerformed
        setDefaultStatusPorts();
    }//GEN-LAST:event_btnStatusDefaultActionPerformed

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        settings.setStatusPorts(statusPortsModel.getAll());
        settings.setDataPorts(dataPortsModel.getAll());

        try {
            settings.write();
        } catch (CannotUpdateSettingException e) {
            LOGGER.error("Could not write MITS 88-SIO settings", e);
            dialogs.showError("Could not write MITS 88-SIO settings. Please see log file for details.", "Save settings");
        }

        dispose();
    }//GEN-LAST:event_btnOKActionPerformed

    private javax.swing.JList<String> lstDataPorts;
    private javax.swing.JList<String> lstStatusPorts;
    // End of variables declaration//GEN-END:variables
}
