/*
 * Copyright (C) 2014 Peter Jakubčo
 *
 * KISS, DRY, YAGNI
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */
package net.sf.emustudio.brainduck.terminal.impl;

import java.net.URL;
import java.util.Objects;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import net.sf.emustudio.brainduck.terminal.io.Cursor;
import net.sf.emustudio.brainduck.terminal.io.Display;
import net.sf.emustudio.brainduck.terminal.io.GUIUtils;
import net.sf.emustudio.brainduck.terminal.io.Keyboard;
import net.sf.emustudio.brainduck.terminal.io.OutputProvider;

public class BrainTerminalDialog extends JDialog implements OutputProvider, Keyboard.KeyboardListener {
    private static final int MAX_COLUMN = 80;
    private static final int MAX_ROW = 25;

    private final ImageIcon blueIcon;
    private final ImageIcon redIcon;
    private final ImageIcon greenIcon;
    
    private final Display canvas;
    private final Keyboard keyboard;

    private BrainTerminalDialog(Keyboard keyboard) {
        URL blueIconURL = getClass().getResource(
                "/net/sf/emustudio/brainduck/terminal/16_circle_blue.png"
        );
        URL redIconURL = getClass().getResource(
                "/net/sf/emustudio/brainduck/terminal/16_circle_red.png"
        );
        URL greenIconURL = getClass().getResource(
                "/net/sf/emustudio/brainduck/terminal/16_circle_green.png"
        );

        blueIcon = new ImageIcon(Objects.requireNonNull(blueIconURL));
        redIcon = new ImageIcon(Objects.requireNonNull(redIconURL));
        greenIcon = new ImageIcon(Objects.requireNonNull(greenIconURL));
        
        this.keyboard = keyboard;

        setTitle("BrainDuck Terminal");
        initComponents();
        setLocationRelativeTo(null);
        
        canvas = new Display(MAX_COLUMN, MAX_ROW);
        scrollPane.setViewportView(canvas);
        canvas.start();
    }

    public static BrainTerminalDialog create(Keyboard keyboard) {
        BrainTerminalDialog dialog = new BrainTerminalDialog(keyboard);
        GUIUtils.addListenerRecursively(dialog, dialog.keyboard);
        dialog.keyboard.addListener(dialog);
        return dialog;
    }

    private void writeStarted() {
        lblStatusIcon.setIcon(redIcon);
        lblStatusIcon.repaint();
    }

    @Override
    public void readStarted() {
        lblStatusIcon.setIcon(greenIcon);
        lblStatusIcon.repaint();
        btnASCII.setEnabled(true);
    }

    @Override
    public void readEnded() {
        lblStatusIcon.setIcon(blueIcon);
        lblStatusIcon.repaint();
        btnASCII.setEnabled(false);
    }

    @Override
    public void reset() {
        canvas.clear();
    }

    @Override
    public void write(int character) {
        writeStarted();
        try {
            Cursor cursor = canvas.getTextCanvasCursor();
            if (character < 32) {
                switch (character) {
                    case 7:  /* bell */
                        break;
                    case 8:  /* backspace*/
                        cursor.back();
                        break;
                    case 9:
                        cursor.advance(4);
                        break;
                    case 0x0A: /* line feed */
                        cursor.newLine();
                        cursor.carriageReturn(); // simulate CR/LF
                        break;
                    case 0x0D: /* carriage return */
                        cursor.carriageReturn();
                        break;
                }
                return;
            }
            canvas.writeAtCursor(character);
        } finally {
            readEnded();
        }
    }

    @Override
    public void showGUI() {
        this.setVisible(true);
    }
    
    @Override
    public void close() {
        canvas.stop();
        GUIUtils.removeListenerRecursively(this, keyboard);
        dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelStatus = new javax.swing.JPanel();
        lblStatusIcon = new javax.swing.JLabel();
        btnASCII = new javax.swing.JButton();
        scrollPane = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblStatusIcon.setIcon(blueIcon);
        lblStatusIcon.setToolTipText("Waiting for input? (red - yes, blue - no)");

        btnASCII.setText("ASCII input");
        btnASCII.setEnabled(false);

        javax.swing.GroupLayout panelStatusLayout = new javax.swing.GroupLayout(panelStatus);
        panelStatus.setLayout(panelStatusLayout);
        panelStatusLayout.setHorizontalGroup(
            panelStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelStatusLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblStatusIcon)
                .addContainerGap(676, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelStatusLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnASCII)
                .addContainerGap())
        );
        panelStatusLayout.setVerticalGroup(
            panelStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblStatusIcon, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(btnASCII, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        scrollPane.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(scrollPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(scrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 387, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnASCII;
    private javax.swing.JLabel lblStatusIcon;
    private javax.swing.JPanel panelStatus;
    private javax.swing.JScrollPane scrollPane;
    // End of variables declaration//GEN-END:variables

}
