/*
 * ArchPreviewDialog.java
 *
 * Created on Piatok, 2008, júl 18, 19:36
 */

package gui;

import javax.swing.GroupLayout;
import javax.swing.JDialog;
import javax.swing.JScrollPane;
import javax.swing.WindowConstants;

import architecture.drawing.PreviewPanel;
import architecture.drawing.Schema;

/**
 *
 * @author  vbmacher
 */
@SuppressWarnings("serial")
public class ArchPreviewDialog extends JDialog {
    private PreviewPanel pan;

    /** Creates new form ArchPreviewDialog */
    public ArchPreviewDialog(JDialog parent, boolean modal, Schema schema) {
        super(parent, modal);
        pan = new PreviewPanel(schema);
        initComponents(pan.getWidth() , pan.getHeight());
        scrollPane.setViewportView(pan);
        this.setLocationRelativeTo(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents(int panelWidth, int panelHeight) {

        scrollPane = new JScrollPane();

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Preview architecture");

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(scrollPane, GroupLayout.DEFAULT_SIZE, panelWidth, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(scrollPane, GroupLayout.DEFAULT_SIZE, panelHeight, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JScrollPane scrollPane;
    // End of variables declaration//GEN-END:variables

}
