/* SPDX-FileCopyrightText: 2006-2026 Peter Jakubčo
   SPDX-License-Identifier: GPL-3.0-or-later */
pluginManagement {
    repositories {
        mavenLocal()
        mavenCentral()
        gradlePluginPortal()
    }
}

rootProject.name = 'emuStudio'

include ':application'

include ':plugins:compiler:as-8080'
include ':plugins:compiler:as-ssem'
include ':plugins:compiler:as-z80'
include ':plugins:compiler:brainc-brainduck'
include ':plugins:compiler:ramc-ram'
include ':plugins:compiler:raspc-rasp'

include ':plugins:cpu:8080-cpu'
include ':plugins:cpu:brainduck-cpu'
include ':plugins:cpu:ram-cpu'
include ':plugins:cpu:rasp-cpu'
include ':plugins:cpu:ssem-cpu'
include ':plugins:cpu:z80-cpu'

include ':plugins:device:88-dcdd'
include ':plugins:device:88-sio'
include ':plugins:device:abstract-tape'
include ':plugins:device:adm3A-terminal'
include ':plugins:device:vt100-terminal'
include ':plugins:device:simh-pseudo'
include ':plugins:device:ssem-display'
include ':plugins:device:zxspectrum-bus'
include ':plugins:device:zxspectrum-ula'
include ':plugins:device:audiotape-player'

include ':plugins:memory:ram-mem'
include ':plugins:memory:rasp-mem'
include ':plugins:memory:ssem-mem'
include ':plugins:memory:byte-mem'

