
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Feb 12 11:38:49 CET 2009
//----------------------------------------------------

package brainduck.impl;

/** CUP generated interface containing symbol constants. */
public interface symBD {
  /* terminals */
  public static final int EOL = 10;
  public static final int DECV = 5;
  public static final int LOOP = 8;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int PRINT = 6;
  public static final int TCOMMENT = 11;
  public static final int LOAD = 7;
  public static final int INC = 2;
  public static final int DEC = 3;
  public static final int INCV = 4;
  public static final int ENDL = 9;
}

