/* The following code was generated by JFlex 1.4.3 on 27.3.2009 12:21 */

/*
 * RAMLexer.java
 *
 * (c) Copyright 2009, P. Jakubčo
 *
 * Lexical analyser for RAM compiler
 *
 * KISS, YAGNI
 */

package ramc_ram.impl;

import plugins.compiler.ILexer;
import plugins.compiler.IToken;
import java.io.Reader;
import java.io.IOException;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 27.3.2009 12:21 from the specification file
 * <tt>lexerRAM.jflex</tt>
 */
public class RAMLexer implements java_cup.runtime.Scanner, ILexer {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int INPUT = 6;
  public static final int STRING = 2;
  public static final int YYINITIAL = 0;
  public static final int IDENTIFIER = 4;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1,  1,  2,  2,  3, 3
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\4\1\3\1\0\1\4\1\2\22\0\1\4\11\0\1\34"+
    "\5\0\12\5\1\7\1\1\1\35\1\33\1\37\2\6\1\11\1\24"+
    "\1\6\1\16\1\15\1\6\1\31\1\10\1\20\1\27\1\6\1\12"+
    "\1\25\1\36\1\21\1\30\1\6\1\14\1\22\1\13\1\23\1\26"+
    "\1\17\2\6\1\32\4\0\1\6\1\0\1\11\1\24\1\6\1\16"+
    "\1\15\1\6\1\31\1\10\1\20\1\27\1\6\1\12\1\25\1\36"+
    "\1\21\1\30\1\6\1\14\1\22\1\13\1\23\1\26\1\17\2\6"+
    "\1\32\uff85\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\4\0\1\1\1\2\2\3\1\4\1\5\12\1\1\6"+
    "\1\7\1\1\1\10\1\11\2\12\1\13\1\14\1\0"+
    "\1\15\13\0\1\16\2\0\1\17\2\0\1\20\2\0"+
    "\1\21\1\22\1\23\2\0\1\24\1\25\1\26\2\0"+
    "\1\27\1\0\1\30\1\31\2\0\1\32";

  private static int [] zzUnpackAction() {
    int [] result = new int[68];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\40\0\100\0\140\0\200\0\240\0\300\0\200"+
    "\0\200\0\340\0\u0100\0\u0120\0\u0140\0\u0160\0\u0180\0\u01a0"+
    "\0\u01c0\0\u01e0\0\u0200\0\u0220\0\200\0\200\0\u0240\0\u0260"+
    "\0\u0280\0\u02a0\0\200\0\u02c0\0\u02e0\0\u0100\0\200\0\u0300"+
    "\0\u0320\0\u0340\0\u0360\0\u0380\0\u03a0\0\u03c0\0\u03e0\0\u0400"+
    "\0\u0420\0\u0440\0\u0100\0\u0460\0\u0480\0\u0100\0\u04a0\0\u04c0"+
    "\0\u0100\0\u04e0\0\u0500\0\u0100\0\u0100\0\u0100\0\u0520\0\u0540"+
    "\0\u0100\0\u0100\0\u0100\0\u0560\0\u0580\0\u0100\0\u05a0\0\u0100"+
    "\0\u0100\0\u05c0\0\u05e0\0\200";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[68];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\5\1\6\1\7\1\10\1\11\1\12\1\13\1\5"+
    "\1\14\1\15\1\16\1\13\1\17\1\13\1\20\1\21"+
    "\2\13\1\22\2\13\1\23\1\13\1\24\3\13\1\25"+
    "\1\26\1\27\1\13\1\5\1\30\1\31\1\32\1\33"+
    "\1\11\33\30\1\5\1\31\1\32\1\33\1\11\1\5"+
    "\1\34\1\5\23\34\3\5\1\34\1\5\1\35\1\31"+
    "\1\32\1\33\1\11\33\35\40\0\2\6\2\0\34\6"+
    "\3\0\1\10\41\0\1\12\37\0\2\36\1\37\23\36"+
    "\3\0\1\36\6\0\2\36\1\37\1\36\1\40\21\36"+
    "\3\0\1\36\6\0\2\36\1\37\6\36\1\41\14\36"+
    "\3\0\1\36\6\0\2\36\1\37\11\36\1\42\11\36"+
    "\3\0\1\36\6\0\2\36\1\37\5\36\1\43\15\36"+
    "\3\0\1\36\6\0\2\36\1\37\10\36\1\44\12\36"+
    "\3\0\1\36\6\0\2\36\1\37\4\36\1\45\16\36"+
    "\3\0\1\36\6\0\2\36\1\37\3\36\1\46\7\36"+
    "\1\47\7\36\3\0\1\36\6\0\2\36\1\37\13\36"+
    "\1\50\7\36\3\0\1\36\6\0\2\36\1\37\15\36"+
    "\1\51\3\36\1\52\1\53\3\0\1\36\21\0\1\54"+
    "\17\0\1\30\4\0\33\30\2\31\2\0\34\31\3\0"+
    "\1\33\41\0\2\34\1\0\23\34\3\0\1\34\1\0"+
    "\1\35\4\0\33\35\5\0\2\36\1\37\2\36\1\55"+
    "\20\36\3\0\1\36\6\0\2\36\1\37\6\36\1\56"+
    "\14\36\3\0\1\36\6\0\2\36\1\37\1\36\1\57"+
    "\21\36\3\0\1\36\6\0\2\36\1\37\1\36\1\60"+
    "\21\36\3\0\1\36\6\0\2\36\1\37\16\36\1\61"+
    "\4\36\3\0\1\36\6\0\2\36\1\37\10\36\1\62"+
    "\12\36\3\0\1\36\6\0\2\36\1\37\11\36\1\63"+
    "\11\36\3\0\1\36\6\0\2\36\1\37\14\36\1\64"+
    "\6\36\3\0\1\36\6\0\2\36\1\37\2\36\1\65"+
    "\20\36\3\0\1\36\6\0\2\36\1\37\20\36\1\66"+
    "\2\36\3\0\1\36\6\0\2\36\1\37\3\36\1\67"+
    "\17\36\3\0\1\36\37\0\1\70\6\0\2\36\1\37"+
    "\3\36\1\71\17\36\3\0\1\36\6\0\2\36\1\37"+
    "\6\36\1\72\14\36\3\0\1\36\6\0\2\36\1\37"+
    "\6\36\1\73\14\36\3\0\1\36\6\0\2\36\1\37"+
    "\3\36\1\74\17\36\3\0\1\36\6\0\2\36\1\37"+
    "\4\36\1\75\16\36\3\0\1\36\6\0\2\36\1\37"+
    "\22\36\1\76\3\0\1\36\31\0\1\77\14\0\2\36"+
    "\1\37\5\36\1\100\15\36\3\0\1\36\6\0\2\36"+
    "\1\37\5\36\1\101\15\36\3\0\1\36\24\0\1\102"+
    "\27\0\1\103\63\0\1\104";

  private static int [] zzUnpackTrans() {
    int [] result = new int[1536];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\4\0\1\11\2\1\2\11\13\1\2\11\4\1\1\11"+
    "\2\1\1\0\1\11\13\0\1\1\2\0\1\1\2\0"+
    "\1\1\2\0\3\1\2\0\3\1\2\0\1\1\1\0"+
    "\2\1\2\0\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[68];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
    @Override
    public tokenRAM getSymbol() throws IOException {
        return next_token();
    }

    @Override
    public void reset(Reader in, int yyline, int yychar, int yycolumn) {
        yyreset(in);
        this.yyline = yyline;
        this.yychar = yychar;
        this.yycolumn = yycolumn;
        yybegin(YYINITIAL);
    }
    
    @Override
    public void reset() {
        yyline = yychar = yycolumn = 0;
        yybegin(YYINITIAL);
    }
    
    private tokenRAM token(int id, int type, Object val, boolean initial) {
        return new tokenRAM(id,type,yytext(),yyline,yycolumn,yychar,val,initial);
    }
    


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public RAMLexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public RAMLexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 144) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public tokenRAM next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 22: 
          { return token(tokenRAM.READ,  IToken.RESERVED,null,true);
          }
        case 27: break;
        case 25: 
          { return token(tokenRAM.STORE, IToken.RESERVED,null,true);
          }
        case 28: break;
        case 20: 
          { return token(tokenRAM.HALT, IToken.RESERVED,null,true);
          }
        case 29: break;
        case 1: 
          { return token(tokenRAM.error, tokenRAM.ERROR,null,false);
          }
        case 30: break;
        case 3: 
          { return token(tokenRAM.EOL, IToken.SEPARATOR,null,true);
          }
        case 31: break;
        case 19: 
          { yybegin(IDENTIFIER); return token(tokenRAM.JMP, IToken.RESERVED,null,true);
          }
        case 32: break;
        case 8: 
          { yybegin(YYINITIAL); return token(tokenRAM.STRING, IToken.LITERAL,yytext(),false);
          }
        case 33: break;
        case 18: 
          { return token(tokenRAM.MUL, IToken.RESERVED,null,true);
          }
        case 34: break;
        case 5: 
          { return token(tokenRAM.NUMBER, IToken.LITERAL,yytext(),true);
          }
        case 35: break;
        case 6: 
          { yybegin(STRING); return token(tokenRAM.DIRECT, IToken.OPERATOR,null,true);
          }
        case 36: break;
        case 7: 
          { return token(tokenRAM.INDIRECT, IToken.OPERATOR,null,true);
          }
        case 37: break;
        case 13: 
          { return token(tokenRAM.LABELL, IToken.LABEL,yytext(),true);
          }
        case 38: break;
        case 26: 
          { yybegin(INPUT); return token(tokenRAM.INPUT, IToken.PREPROCESSOR, null,true);
          }
        case 39: break;
        case 11: 
          { yybegin(YYINITIAL); return token(tokenRAM.IDENT, IToken.IDENTIFIER,yytext(),false);
          }
        case 40: break;
        case 21: 
          { return token(tokenRAM.LOAD, IToken.RESERVED,null,true);
          }
        case 41: break;
        case 9: 
          { yybegin(YYINITIAL); return token(tokenRAM.TCOMMENT, IToken.COMMENT,null,false);
          }
        case 42: break;
        case 10: 
          { yybegin(YYINITIAL); return token(tokenRAM.EOL, IToken.SEPARATOR,null,false);
          }
        case 43: break;
        case 2: 
          { yybegin(YYINITIAL); return token(tokenRAM.TCOMMENT, IToken.COMMENT,null,true);
          }
        case 44: break;
        case 17: 
          { return token(tokenRAM.SUB, IToken.RESERVED,null,true);
          }
        case 45: break;
        case 14: 
          { yybegin(IDENTIFIER); return token(tokenRAM.JZ, IToken.RESERVED,null,true);
          }
        case 46: break;
        case 23: 
          { yybegin(IDENTIFIER); return token(tokenRAM.JGTZ, IToken.RESERVED,null,true);
          }
        case 47: break;
        case 16: 
          { return token(tokenRAM.DIV, IToken.RESERVED,null,true);
          }
        case 48: break;
        case 24: 
          { return token(tokenRAM.WRITE,  IToken.RESERVED,null,true);
          }
        case 49: break;
        case 15: 
          { return token(tokenRAM.ADD,IToken.RESERVED,null,true);
          }
        case 50: break;
        case 4: 
          { 
          }
        case 51: break;
        case 12: 
          { return token(tokenRAM.STRING, IToken.PREPROCESSOR,yytext(),false);
          }
        case 52: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              {   return token(tokenRAM.EOF, IToken.TEOF,null,false);
 }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
