/* SPDX-FileCopyrightText: 2006-2026 Peter Jakubčo
   SPDX-License-Identifier: GPL-3.0-or-later */

plugins {
  id 'java'
  id 'com.adarshr.test-logger' version '4.0.0'
}

dependencies {
  implementation libs.emuLib
  implementation libs.slf4JApi

  testImplementation libs.junit
  testImplementation libs.slf4JSimple
  testImplementation libs.easyMock
}

apply from: "$rootDir/gradle/conventions/java-conventions.gradle"
