
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Mar 23 09:49:13 CET 2009
//----------------------------------------------------

package ram.impl;

/** CUP generated interface containing symbol constants. */
public interface symRAM {
  /* terminals */
  public static final int INDIRECT = 15;
  public static final int READ = 5;
  public static final int IDENT = 17;
  public static final int DIRECT = 14;
  public static final int JZ = 12;
  public static final int WRITE = 6;
  public static final int JMP = 11;
  public static final int SUB = 8;
  public static final int EOL = 13;
  public static final int LABELL = 18;
  public static final int EOF = 0;
  public static final int NUMBER = 16;
  public static final int TCOMMENT = 19;
  public static final int DIV = 10;
  public static final int ADD = 7;
  public static final int LOAD = 3;
  public static final int error = 1;
  public static final int HALT = 2;
  public static final int STORE = 4;
  public static final int MUL = 9;
}

