/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sk.tuke.emustudio.rasp.cpu.gui;

import emulib.plugins.cpu.CPU;
import sk.tuke.emustudio.rasp.cpu.impl.RASPEmulatorImpl;
import sk.tuke.emustudio.rasp.memory.impl.RASPMemoryContextImpl;

/**
 *
 * @author miso
 */
public class RASPCpuStatusPanel extends javax.swing.JPanel {

    /**
     * Creates new form RASPCpuStatusPanel
     *
     * @param cpu
     * @param memory
     */
    public RASPCpuStatusPanel(RASPEmulatorImpl cpu, RASPMemoryContextImpl memory) {
        initComponents();
        cpu.addCPUListener(new CPU.CPUListener() {

            @Override
            public void runStateChanged(CPU.RunState state) {
                switch (state) {
                    case STATE_STOPPED_NORMAL:
                        runState.setText("NORMAL  - STOPPED");
                        break;
                    case STATE_STOPPED_BREAK:
                        runState.setText("BREAKPOINT");
                        break;
                    case STATE_STOPPED_ADDR_FALLOUT:
                        runState.setText("ADDRESS FALLOUT - STOPPED");
                        break;
                    case STATE_STOPPED_BAD_INSTR:
                        runState.setText("INSTRUCTION FALLOUT - STOPPED");
                        break;
                }
            }

            @Override
            public void internalStateChanged() {
                //accumulator is changed
                accValue.setText(String.valueOf(cpu.getACC()));
                //IP changed
                instrPointerValue.setText(String.valueOf(cpu.getInstructionPosition()));
            }

        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        accValue = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        instrPointerValue = new javax.swing.JTextPane();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        runState = new javax.swing.JTextPane();

        jLabel1.setText("ACCUMULATOR (R0):");

        jLabel2.setText("INSTRUCTION POINTER (IP):");

        accValue.setEditable(false);
        accValue.setText("0");
        jScrollPane1.setViewportView(accValue);

        instrPointerValue.setEditable(false);
        instrPointerValue.setText("0");
        jScrollPane2.setViewportView(instrPointerValue);

        jLabel3.setText("RUNNING STATUS:");

        runState.setEditable(false);
        jScrollPane3.setViewportView(runState);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(146, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextPane accValue;
    private javax.swing.JTextPane instrPointerValue;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextPane runState;
    // End of variables declaration//GEN-END:variables
}
