/*
 * FindDialog.java
 *
 * Created on ${date}, 11:26
 * hold to: KISS, YAGNI
 *
 */

package emu8.gui;

import java.util.ArrayList;
import java.util.regex.Matcher;
import javax.swing.ComboBoxModel;
import javax.swing.event.ListDataListener;

/**
 *
 * @author  vbmacher
 */
public class FindDialog extends javax.swing.JDialog {
    private static Matcher matcher = null;
    private static int radioDirection = 0;
    private static byte checks = 0;
    private static ArrayList list = new ArrayList();
    
    /** Creates new form FindDialog */
    public FindDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        switch(radioDirection) {
            case 0: endRadio.setSelected(true); break;
            case 1: startRadio.setSelected(true); break;
            case 2: allRadio.setSelected(true); break;
        }
        if ((checks & 1) != 0) caseCheck.setSelected(true);
        if ((checks & 2) != 0) wholeCheck.setSelected(true);
        if ((checks & 4) != 0) regularCheck.setSelected(true);
        
        searchCombo.setModel(new ComboBoxModel() {
            private int in = -1;
            public void setSelectedItem(Object anItem) {
                in = list.indexOf(anItem);
            }
            public Object getSelectedItem() {
                if (in != -1) return list.get(in);
                else return null;
            }
            public int getSize() { return list.size(); }
            public Object getElementAt(int index) {
                return list.get(index);
            }
            public void addListDataListener(ListDataListener l) {}
            public void removeListDataListener(ListDataListener l) {}
        });        
        this.setLocationRelativeTo(parent);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.ButtonGroup buttonGroup1 = new javax.swing.ButtonGroup();
        javax.swing.JLabel jLabel1 = new javax.swing.JLabel();
        searchCombo = new javax.swing.JComboBox();
        javax.swing.JPanel jPanel1 = new javax.swing.JPanel();
        caseCheck = new javax.swing.JCheckBox();
        wholeCheck = new javax.swing.JCheckBox();
        regularCheck = new javax.swing.JCheckBox();
        javax.swing.JPanel jPanel2 = new javax.swing.JPanel();
        endRadio = new javax.swing.JRadioButton();
        startRadio = new javax.swing.JRadioButton();
        allRadio = new javax.swing.JRadioButton();
        javax.swing.JButton searchButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Find text");
        setResizable(false);

        jLabel1.setText("Search:");

        searchCombo.setEditable(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Options"));

        caseCheck.setText("Case sensitive");

        wholeCheck.setText("Only whole words");

        regularCheck.setText("Regular expression");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(caseCheck)
                    .addComponent(wholeCheck)
                    .addComponent(regularCheck))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(caseCheck)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(wholeCheck)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(regularCheck)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Direction"));

        buttonGroup1.add(endRadio);
        endRadio.setSelected(true);
        endRadio.setText("To end of document");

        buttonGroup1.add(startRadio);
        startRadio.setText("To start of document");

        buttonGroup1.add(allRadio);
        allRadio.setText("All document");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(endRadio)
                    .addComponent(startRadio)
                    .addComponent(allRadio))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(endRadio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(startRadio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(allRadio)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(354, Short.MAX_VALUE)
                .addComponent(searchButton)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(searchCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(searchButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        if (endRadio.isSelected()) radioDirection = 0;
        else if (startRadio.isSelected()) radioDirection = 1;
        else radioDirection = 2;
        if (caseCheck.isSelected()) checks |= 1;
        else checks &= 6;
        if (wholeCheck.isSelected()) checks |= 2;
        else checks &= 5;
        if (regularCheck.isSelected()) checks |= 4;
        else checks &= 3;
        if (!list.contains((String)searchCombo.getEditor().getItem()))
            list.add((String)searchCombo.getEditor().getItem());
    }//GEN-LAST:event_searchButtonActionPerformed
  
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JRadioButton allRadio;
    javax.swing.JCheckBox caseCheck;
    javax.swing.JRadioButton endRadio;
    javax.swing.JCheckBox regularCheck;
    javax.swing.JComboBox searchCombo;
    javax.swing.JRadioButton startRadio;
    javax.swing.JCheckBox wholeCheck;
    // End of variables declaration//GEN-END:variables
    
}
