/* SPDX-FileCopyrightText: 2006-2026 Peter Jakubčo
   SPDX-License-Identifier: GPL-3.0-or-later */

plugins {
  id 'java'
  id 'net.emustudio.edigen-gradle-plugin' version '1.6.0-SNAPSHOT'
  id 'com.adarshr.test-logger' version '4.0.0'
  id 'jacoco'
}

dependencies {
  implementation libs.emuLib
  implementation libs.jcipAnnotations
  implementation libs.slf4JApi

  testImplementation libs.cpuTestSuite
  testImplementation libs.junit
  testImplementation libs.easyMock
  testImplementation libs.slf4JSimple
}

edigen {
  decoderName = 'net.emustudio.plugins.cpu.intel8080.gui.DecoderImpl'
  disassemblerName = 'net.emustudio.plugins.cpu.intel8080.gui.DisassemblerImpl'
}

apply from: "$rootDir/gradle/conventions/java-conventions.gradle"

test {
  finalizedBy jacocoTestReport // report is always generated after tests run
}

jacocoTestReport {
  dependsOn test // tests are required to run before generating the report
}
