/*
 * frmViewConfig.java
 *
 * Created on Utorok, 2007, september 11, 15:42
 */

package emu8;

import java.awt.event.*;
import java.util.*;

import plugins.device.IDevice;
/**
 *
 * @author  vbmacher
 */
public class frmViewConfig extends javax.swing.JFrame {
    private emuConfiguration emuConfig;

    
    /** Creates new form frmViewConfig */
    public frmViewConfig(emuConfiguration emuConfig) {
        this.emuConfig = emuConfig;
        initComponents();
        
        try {
            lblName.setText(emuConfig.nowName);
            lblCompilerFileName.setText(emuConfig.nowCompiler+".jar");
            lblCompilerName.setText(emuConfig.cCompiler.getName());
            lblCompilerVersion.setText(emuConfig.cCompiler.getVersion());
            txtCompilerDescription.setText(emuConfig.cCompiler.getDescription());
            
            lblCPUFileName.setText(emuConfig.nowCPU+".jar");
            lblCPUName.setText(emuConfig.cCPU.getName());
            lblCPUVersion.setText(emuConfig.cCPU.getVersion());
            txtCPUDescription.setText(emuConfig.cCPU.getDescription());
            
            lblMemoryFileName.setText(emuConfig.nowMemory+".jar");
            lblMemoryName.setText(emuConfig.cMemory.getName());
            lblMemoryVersion.setText(emuConfig.cMemory.getVersion());
            txtMemoryDescription.setText(emuConfig.cMemory.getDescription());
        }
        catch (NullPointerException e) {}
        
        for (int i = 0; i < emuConfig.nowDevices.size(); i++)
            cmbDevice.addItem(emuConfig.nowDevices.get(i));
        
        if (cmbDevice.getItemCount() > 0) showDevConfig(0);
        cmbDevice.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                int i = cmbDevice.getSelectedIndex();
                try { showDevConfig(i); }
                catch(Exception ex) {}
            }
            
        });
        this.setLocationRelativeTo(null);
    }
    
    private void showDevConfig(int i) {
        lblDeviceFileName.setText(emuConfig.nowDevices.get(i)+".jar");
        lblDeviceName.setText(((IDevice)emuConfig.cDevices.get(i))
            .getName());
        lblDeviceVersion.setText(((IDevice)emuConfig.cDevices.get(i))
            .getVersion());
        txtDeviceDescription.setText(((IDevice)emuConfig.cDevices.get(i))
            .getDescription());
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblName = new javax.swing.JLabel();
        javax.swing.JTabbedPane jTabbedPane1 = new javax.swing.JTabbedPane();
        javax.swing.JPanel jPanel1 = new javax.swing.JPanel();
        javax.swing.JLabel jLabel1 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel2 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel3 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel4 = new javax.swing.JLabel();
        lblCompilerVersion = new javax.swing.JLabel();
        lblCompilerName = new javax.swing.JLabel();
        lblCompilerFileName = new javax.swing.JLabel();
        javax.swing.JScrollPane jScrollPane1 = new javax.swing.JScrollPane();
        txtCompilerDescription = new javax.swing.JTextArea();
        javax.swing.JPanel jPanel2 = new javax.swing.JPanel();
        javax.swing.JLabel jLabel5 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel6 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel7 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel8 = new javax.swing.JLabel();
        lblCPUVersion = new javax.swing.JLabel();
        lblCPUName = new javax.swing.JLabel();
        lblCPUFileName = new javax.swing.JLabel();
        javax.swing.JScrollPane jScrollPane2 = new javax.swing.JScrollPane();
        txtCPUDescription = new javax.swing.JTextArea();
        javax.swing.JPanel jPanel3 = new javax.swing.JPanel();
        javax.swing.JLabel jLabel9 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel10 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel11 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel12 = new javax.swing.JLabel();
        lblMemoryFileName = new javax.swing.JLabel();
        lblMemoryName = new javax.swing.JLabel();
        lblMemoryVersion = new javax.swing.JLabel();
        javax.swing.JScrollPane jScrollPane3 = new javax.swing.JScrollPane();
        txtMemoryDescription = new javax.swing.JTextArea();
        javax.swing.JPanel jPanel4 = new javax.swing.JPanel();
        javax.swing.JLabel jLabel13 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel14 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel15 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel16 = new javax.swing.JLabel();
        lblDeviceFileName = new javax.swing.JLabel();
        lblDeviceName = new javax.swing.JLabel();
        lblDeviceVersion = new javax.swing.JLabel();
        javax.swing.JScrollPane jScrollPane4 = new javax.swing.JScrollPane();
        txtDeviceDescription = new javax.swing.JTextArea();
        javax.swing.JLabel jLabel17 = new javax.swing.JLabel();
        cmbDevice = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("View current configuration");
        setAlwaysOnTop(true);
        setResizable(false);

        lblName.setFont(lblName.getFont().deriveFont(lblName.getFont().getStyle() | java.awt.Font.BOLD));
        lblName.setText(null);

        jTabbedPane1.setFocusable(false);

        jLabel1.setText("File name:");

        jLabel2.setText("Plugin name:");

        jLabel3.setText("Plugin version:");

        jLabel4.setText("Description:");

        lblCompilerVersion.setFont(lblCompilerVersion.getFont().deriveFont(lblCompilerVersion.getFont().getStyle() | java.awt.Font.BOLD));

        lblCompilerName.setFont(lblCompilerName.getFont().deriveFont(lblCompilerName.getFont().getStyle() | java.awt.Font.BOLD));

        lblCompilerFileName.setFont(lblCompilerFileName.getFont().deriveFont(lblCompilerFileName.getFont().getStyle() | java.awt.Font.BOLD));

        txtCompilerDescription.setEditable(false);
        txtCompilerDescription.setFont(new java.awt.Font("Monospaced", 0, 12));
        txtCompilerDescription.setLineWrap(true);
        txtCompilerDescription.setRows(5);
        txtCompilerDescription.setWrapStyleWord(true);
        txtCompilerDescription.setOpaque(false);
        jScrollPane1.setViewportView(txtCompilerDescription);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblCompilerFileName, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCompilerName, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCompilerVersion, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblCompilerFileName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblCompilerName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblCompilerVersion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                    .addComponent(jLabel4))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Compiler", jPanel1);

        jLabel5.setText("File name:");

        jLabel6.setText("Plugin name:");

        jLabel7.setText("Plugin version:");

        jLabel8.setText("Description:");

        lblCPUVersion.setFont(lblCPUVersion.getFont().deriveFont(lblCPUVersion.getFont().getStyle() | java.awt.Font.BOLD));

        lblCPUName.setFont(lblCPUName.getFont().deriveFont(lblCPUName.getFont().getStyle() | java.awt.Font.BOLD));

        lblCPUFileName.setFont(lblCPUFileName.getFont().deriveFont(lblCPUFileName.getFont().getStyle() | java.awt.Font.BOLD));

        txtCPUDescription.setEditable(false);
        txtCPUDescription.setFont(new java.awt.Font("Monospaced", 0, 12));
        txtCPUDescription.setLineWrap(true);
        txtCPUDescription.setRows(5);
        txtCPUDescription.setWrapStyleWord(true);
        txtCPUDescription.setOpaque(false);
        jScrollPane2.setViewportView(txtCPUDescription);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCPUFileName)
                    .addComponent(lblCPUName)
                    .addComponent(lblCPUVersion)
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lblCPUFileName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lblCPUName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lblCPUVersion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("CPU", jPanel2);

        jLabel9.setText("File name:");

        jLabel10.setText("Plugin name:");

        jLabel11.setText("Plugin version:");

        jLabel12.setText("Description:");

        lblMemoryFileName.setFont(lblMemoryFileName.getFont().deriveFont(lblMemoryFileName.getFont().getStyle() | java.awt.Font.BOLD));

        lblMemoryName.setFont(lblMemoryName.getFont().deriveFont(lblMemoryName.getFont().getStyle() | java.awt.Font.BOLD));

        lblMemoryVersion.setFont(lblMemoryVersion.getFont().deriveFont(lblMemoryVersion.getFont().getStyle() | java.awt.Font.BOLD));

        txtMemoryDescription.setEditable(false);
        txtMemoryDescription.setFont(new java.awt.Font("Monospaced", 0, 12));
        txtMemoryDescription.setLineWrap(true);
        txtMemoryDescription.setRows(5);
        txtMemoryDescription.setWrapStyleWord(true);
        txtMemoryDescription.setOpaque(false);
        jScrollPane3.setViewportView(txtMemoryDescription);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMemoryFileName)
                    .addComponent(lblMemoryVersion)
                    .addComponent(lblMemoryName)
                    .addComponent(jScrollPane3))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(lblMemoryFileName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(lblMemoryName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(lblMemoryVersion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Memory", jPanel3);

        jLabel13.setText("File name:");

        jLabel14.setText("Plugin name:");

        jLabel15.setText("Plugin version:");

        jLabel16.setText("Description:");

        lblDeviceFileName.setFont(lblDeviceFileName.getFont().deriveFont(lblDeviceFileName.getFont().getStyle() | java.awt.Font.BOLD));

        lblDeviceName.setFont(lblDeviceName.getFont().deriveFont(lblDeviceName.getFont().getStyle() | java.awt.Font.BOLD));

        lblDeviceVersion.setFont(lblDeviceVersion.getFont().deriveFont(lblDeviceVersion.getFont().getStyle() | java.awt.Font.BOLD));

        txtDeviceDescription.setEditable(false);
        txtDeviceDescription.setFont(new java.awt.Font("Monospaced", 0, 12));
        txtDeviceDescription.setLineWrap(true);
        txtDeviceDescription.setRows(5);
        txtDeviceDescription.setWrapStyleWord(true);
        txtDeviceDescription.setOpaque(false);
        jScrollPane4.setViewportView(txtDeviceDescription);

        jLabel17.setText("Device:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17))
                .addGap(6, 6, 6)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDeviceName)
                    .addComponent(lblDeviceFileName)
                    .addComponent(lblDeviceVersion)
                    .addComponent(jScrollPane4)
                    .addComponent(cmbDevice, 0, 311, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(cmbDevice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(lblDeviceFileName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(lblDeviceName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(lblDeviceVersion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Devices", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
                    .addComponent(lblName))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JComboBox cmbDevice;
    javax.swing.JLabel lblCPUFileName;
    javax.swing.JLabel lblCPUName;
    javax.swing.JLabel lblCPUVersion;
    javax.swing.JLabel lblCompilerFileName;
    javax.swing.JLabel lblCompilerName;
    javax.swing.JLabel lblCompilerVersion;
    javax.swing.JLabel lblDeviceFileName;
    javax.swing.JLabel lblDeviceName;
    javax.swing.JLabel lblDeviceVersion;
    javax.swing.JLabel lblMemoryFileName;
    javax.swing.JLabel lblMemoryName;
    javax.swing.JLabel lblMemoryVersion;
    javax.swing.JLabel lblName;
    javax.swing.JTextArea txtCPUDescription;
    javax.swing.JTextArea txtCompilerDescription;
    javax.swing.JTextArea txtDeviceDescription;
    javax.swing.JTextArea txtMemoryDescription;
    // End of variables declaration//GEN-END:variables
    
}
