/* SPDX-FileCopyrightText: 2006-2026 Peter Jakubčo
   SPDX-License-Identifier: GPL-3.0-or-later */

plugins {
  id 'java'
  id 'net.emustudio.edigen-gradle-plugin' version '1.5.3.1-SNAPSHOT'
  id 'com.adarshr.test-logger' version '4.0.0'
}

repositories {
  mavenLocal()
  mavenCentral()
}

dependencies {
  implementation libs.emuLib
  implementation libs.slf4JApi

  testImplementation libs.cpuTestSuite
  testImplementation libs.junit
  testImplementation libs.easyMock
  testImplementation libs.slf4JSimple
}

edigen {
  decoderName = 'net.emustudio.plugins.cpu.ssem.DecoderImpl'
  disassemblerName = 'net.emustudio.plugins.cpu.ssem.DisassemblerImpl'
}

apply from: "$rootDir/gradle/conventions/java-conventions.gradle"
