/* SPDX-FileCopyrightText: 2006-2026 Peter Jakubčo
   SPDX-License-Identifier: GPL-3.0-or-later */
import org.apache.tools.ant.filters.ReplaceTokens

buildscript {
  repositories {
    mavenLocal()
    mavenCentral()
  }
}

plugins {
  id 'java'
  id 'net.emustudio.edigen-plugin' version '1.5.3-SNAPSHOT'
  id 'com.adarshr.test-logger' version '4.0.0'
}

repositories {
  mavenLocal()
  mavenCentral()
}

dependencies {
  implementation libs.emuLib
  implementation libs.migLayout
  implementation libs.slf4JApi

  testImplementation libs.cpuTestSuite
  testImplementation libs.junit
  testImplementation libs.easyMock
  testImplementation libs.slf4JSimple
}

jar {
  archiveVersion = ''
  manifest {
    attributes manifestAttributes('')
  }
}


edigen {
  decoderName = 'net.emustudio.plugins.cpu.ssem.DecoderImpl'
  disassemblerName = 'net.emustudio.plugins.cpu.ssem.DisassemblerImpl'
}

processResources {
  filesMatching("**/*.properties") {
    filter ReplaceTokens, tokens: [
            "project.version": project.version,
            "today.year"     : new Date().format("yyyy")
    ]
  }
}

compileJava.options.encoding = 'UTF-8'
compileTestJava.options.encoding = 'UTF-8'
javadoc.options.encoding = 'UTF-8'
