/* SPDX-FileCopyrightText: 2006-2026 Peter Jakubčo
   SPDX-License-Identifier: GPL-3.0-or-later */

plugins {
  id 'java'
  id 'com.adarshr.test-logger' version '4.0.0'
}

ext.moduleMainClass = 'net.emustudio.plugins.device.mits88dcdd.cmdline.Runner'

dependencies {
  implementation libs.emuLib
  implementation libs.jcipAnnotations
  implementation libs.slf4JApi
  implementation libs.picocli
  annotationProcessor libs.picocliAnnotation
  implementation libs.tomlj

  cpuLib project(":plugins:cpu:8080-cpu")

  testImplementation libs.junit
  testImplementation libs.easyMock
  testImplementation libs.slf4JSimple
}

apply from: "$rootDir/gradle/conventions/java-conventions.gradle"

compileJava {
  options.compilerArgs += ["-Aproject=${project.group}/${project.name}"]
}

copy {
  from('src/main/scripts')
  into "$buildDir/libs/scripts"
}

copy {
  from('src/main/files')
  into "$buildDir/libs/files"
}
