name = "ZX Spectrum 48K"

[MEMORY]
	schemaPoint = "80,180"
	path = "byte-mem.jar"
	name = "byte-mem"
	id = "1e13a25d-fb23-4061-853a-5fe996b03281"
	type = "MEMORY"

	[MEMORY.settings]
		#memorySize = 49152
		banksCount = 0
		imageName0 = "/home/vbmacher/tmp/emuStudio/examples/zxspectrum-48k/48.rom"  # TODO: change!
		imageBank1 = 0
		imageBank0 = 0
		commonBoundary = 0
		imageAddress0 = 0

#       memorySize = 65536
# ROM areas are stored as pairs ROMfromN and ROMtoN, where N is 0-based counter. There can be multiple rom areas.
#       ROMfromN = someAddress
#       ROMtoN = someAddress
# Memory "images" (files) will be loaded at startup into memory. They are stored here as triplet:
# - imageNameN (file name),
# - imageAddressN (address where the file will be loaded),
# - imageBankN (if memory has >1 banksCount, then number of bank; 0 otherwise)
#
# where N is a 0-based counter
#       imageNameN = imageFileName  # if the suffix ends with ".hex", the format will be Intel HEX; otherwise it will be binary
#       imageAddressN = ...
#       imageBankN = 0
[COMPILER]
	schemaPoint = "80,60"
	path = "as-z80.jar"
	settings = {}
	name = "as-z80"
	id = "9233e0c2-b53c-41e7-9eca-bbb264fcd9da"
	type = "COMPILER"

[CPU]
	schemaPoint = "260,300"
	path = "z80-cpu.jar"
	name = "z80-cpu"
	id = "b86d4bc2-632c-46e3-bba1-c088c9177983"
	type = "CPU"

	[CPU.settings]
		frequency_khz = 3500

# Uncomment the following for specific settings (and remove settings = {} above)
#    [CPU.settings]
#        printCode = true
#        printCodeUseCache = true
#        printCodeFileName = "syserr"   # Or custom path to a file
[[DEVICE]]
	schemaPoint = "420,60"
	path = "zxspectrum-ula.jar"
	settings = {}
	name = "zxspectrum-ula"
	id = "1436ac2d-982f-4a52-b7c6-ecb6f2a0440d"
	type = "DEVICE"

[[DEVICE]]
	schemaPoint = "420,180"
	path = "audiotape-player.jar"
	settings = {}
	name = "audiotape-player"
	id = "581cc598-3beb-4a67-b1e3-b4ec1731a9a7"
	type = "DEVICE"

[[DEVICE]]
	schemaPoint = "260,180"
	path = "zxspectrum-bus.jar"
	settings = {}
	name = "zxspectrum-bus"
	id = "c16f6ea4-c26f-4dbf-972b-893c22a0d92c"
	type = "DEVICE"

[[connections]]
	bidirectional = true
	from = "9233e0c2-b53c-41e7-9eca-bbb264fcd9da"
	to = "1e13a25d-fb23-4061-853a-5fe996b03281"
	points = []

[[connections]]
	bidirectional = true
	from = "1e13a25d-fb23-4061-853a-5fe996b03281"
	to = "c16f6ea4-c26f-4dbf-972b-893c22a0d92c"
	points = []

[[connections]]
	bidirectional = true
	from = "1436ac2d-982f-4a52-b7c6-ecb6f2a0440d"
	to = "c16f6ea4-c26f-4dbf-972b-893c22a0d92c"
	points = ["260,60"]

[[connections]]
	bidirectional = true
	from = "581cc598-3beb-4a67-b1e3-b4ec1731a9a7"
	to = "c16f6ea4-c26f-4dbf-972b-893c22a0d92c"
	points = []

[[connections]]
	bidirectional = true
	from = "c16f6ea4-c26f-4dbf-972b-893c22a0d92c"
	to = "b86d4bc2-632c-46e3-bba1-c088c9177983"
	points = []

