/*
 * DiskFrame.java
 *
 * Created on Streda, 2008, február 6, 8:01
 */

package disk.gui;

import disk.DiskImpl;
import disk.Drive;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;

/**
 *
 * @author  vbmacher
 */
public class DiskFrame extends javax.swing.JFrame {
    private ArrayList drives;
    private int driveInfoIndex = -1; // drive that wants to show current params
    
    /** Creates new form DiskFrame */
    public DiskFrame(ArrayList drives) {
        initComponents();
        this.drives = drives;
        driveCombo.setSelectedIndex(0);
        this.setLocationRelativeTo(null);
        
        for (int i = 0; i < drives.size(); i++)
            updateSelGUI(i);
    }

    private void updateDriveInfo() {
        Drive d = ((Drive)drives.get(driveInfoIndex));
        lblHead.setText((d.getHeadLoaded())?"loaded":"unloaded");
        lblSector.setText(String.valueOf(d.getSector()));
        lblTrack.setText(String.valueOf(d.getTrack()));
        lblOffset.setText(String.valueOf(d.getOffset()));
    }
    
    // called from DiskImpl.java
    public void driveParamsChanged(int drive, boolean headL, int sec, int track, int off) {
        if (drive != driveInfoIndex) return;
        lblHead.setText((headL)?"loaded":"unloaded");
        lblSector.setText(String.valueOf(sec));
        lblTrack.setText(String.valueOf(track));
        lblOffset.setText(String.valueOf(off));
    }
    
    private void updateGUI(int drive) {
        File f = ((Drive)drives.get(drive)).getImageFile();
        if (f != null) {
            txtImage.setText(f.getAbsolutePath());
            umountButton.setEnabled(true);
        } else {
            txtImage.setText("");
            umountButton.setEnabled(false);
        }
    }
    
    private void updateSelGUI(int drive) {
        if (((Drive)drives.get(drive)).isSelected())
            select(drive, true);
        else select(drive,false);
    }
    
    // calling from DiskImpl
    public void select(int drive, boolean sel) {
        String fil;
        if (sel) fil = "/resources/on.gif";
        else fil = "/resources/off.gif";
        switch (drive) {
            case 0: btn0.setIcon(new ImageIcon(getClass().getResource(fil)));break;
            case 1: btn1.setIcon(new ImageIcon(getClass().getResource(fil)));break;
            case 2: btn2.setIcon(new ImageIcon(getClass().getResource(fil)));break;
            case 3: btn3.setIcon(new ImageIcon(getClass().getResource(fil)));break;
            case 4: btn3.setIcon(new ImageIcon(getClass().getResource(fil)));break;
            case 5: btn5.setIcon(new ImageIcon(getClass().getResource(fil)));break;
            case 6: btn6.setIcon(new ImageIcon(getClass().getResource(fil)));break;
            case 7: btn7.setIcon(new ImageIcon(getClass().getResource(fil)));break;
            case 8: btn8.setIcon(new ImageIcon(getClass().getResource(fil)));break;
            case 9: btn9.setIcon(new ImageIcon(getClass().getResource(fil)));break;
            case 10: btn10.setIcon(new ImageIcon(getClass().getResource(fil)));break;
            case 11: btn11.setIcon(new ImageIcon(getClass().getResource(fil)));break;
            case 12: btn12.setIcon(new ImageIcon(getClass().getResource(fil)));break;
            case 13: btn13.setIcon(new ImageIcon(getClass().getResource(fil)));break;
            case 14: btn14.setIcon(new ImageIcon(getClass().getResource(fil)));break;
            case 15: btn15.setIcon(new ImageIcon(getClass().getResource(fil)));break;
        }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        drivesGroup = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        configPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        driveCombo = new javax.swing.JComboBox();
        jLabel17 = new javax.swing.JLabel();
        txtImage = new javax.swing.JTextField();
        browseButton = new javax.swing.JButton();
        mountButton = new javax.swing.JButton();
        umountButton = new javax.swing.JButton();
        createButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        alwaysCheck = new javax.swing.JCheckBox();
        runtimePanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btn0 = new javax.swing.JToggleButton();
        btn1 = new javax.swing.JToggleButton();
        btn2 = new javax.swing.JToggleButton();
        btn3 = new javax.swing.JToggleButton();
        btn4 = new javax.swing.JToggleButton();
        btn5 = new javax.swing.JToggleButton();
        btn6 = new javax.swing.JToggleButton();
        btn7 = new javax.swing.JToggleButton();
        btn8 = new javax.swing.JToggleButton();
        btn9 = new javax.swing.JToggleButton();
        btn10 = new javax.swing.JToggleButton();
        btn11 = new javax.swing.JToggleButton();
        btn12 = new javax.swing.JToggleButton();
        btn13 = new javax.swing.JToggleButton();
        btn14 = new javax.swing.JToggleButton();
        btn15 = new javax.swing.JToggleButton();
        driveInfoPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblSector = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblTrack = new javax.swing.JLabel();
        lblHead = new javax.swing.JLabel();
        lblOffset = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("MITS 88-DISK (floppy)");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Mounted images"));

        driveCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Drive 0 (A)", "Drive 1 (B)", "Drive 2 (C)", "Drive 3 (D)", "Drive 4 (E)", "Drive 5 (F)", "Drive 6 (G)", "Drive 7 (H)", "Drive 8 (I)", "Drive 9 (J)", "Drive 10 (K)", "Drive 11 (L)", "Drive 12 (M)", "Drive 13 (N)", "Drive 14 (O)", "Drive 15 (P)" }));
        driveCombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                driveComboItemStateChanged(evt);
            }
        });

        jLabel17.setText("Image:");

        txtImage.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                txtImageInputMethodTextChanged(evt);
            }
        });

        browseButton.setText("Browse...");
        browseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseButtonActionPerformed(evt);
            }
        });

        mountButton.setText("Mount");
        mountButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mountButtonActionPerformed(evt);
            }
        });

        umountButton.setText("Un-mount");
        umountButton.setEnabled(false);
        umountButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                umountButtonActionPerformed(evt);
            }
        });

        createButton.setText("Create new image");
        createButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(driveCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(txtImage, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(browseButton)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(mountButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(umountButton)
                        .addContainerGap(214, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(createButton)
                        .addContainerGap(216, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(driveCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(browseButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mountButton)
                    .addComponent(umountButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(createButton)
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Other"));

        alwaysCheck.setText("Always on top");
        alwaysCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alwaysCheckActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(alwaysCheck)
                .addContainerGap(232, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(alwaysCheck)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout configPanelLayout = new javax.swing.GroupLayout(configPanel);
        configPanel.setLayout(configPanelLayout);
        configPanelLayout.setHorizontalGroup(
            configPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(configPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(configPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        configPanelLayout.setVerticalGroup(
            configPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(configPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Configuration", configPanel);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Selected drives"));

        drivesGroup.add(btn0);
        btn0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/off.gif"))); // NOI18N
        btn0.setText("A");
        btn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn0ActionPerformed(evt);
            }
        });

        drivesGroup.add(btn1);
        btn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/off.gif"))); // NOI18N
        btn1.setText("B");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });

        drivesGroup.add(btn2);
        btn2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/off.gif"))); // NOI18N
        btn2.setText("C");
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });

        drivesGroup.add(btn3);
        btn3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/off.gif"))); // NOI18N
        btn3.setText("D");
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });

        drivesGroup.add(btn4);
        btn4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/off.gif"))); // NOI18N
        btn4.setText("E");
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });

        drivesGroup.add(btn5);
        btn5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/off.gif"))); // NOI18N
        btn5.setText("F");
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });

        drivesGroup.add(btn6);
        btn6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/off.gif"))); // NOI18N
        btn6.setText("G");
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });

        drivesGroup.add(btn7);
        btn7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/off.gif"))); // NOI18N
        btn7.setText("H");
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });

        drivesGroup.add(btn8);
        btn8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/off.gif"))); // NOI18N
        btn8.setText("I");
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });

        drivesGroup.add(btn9);
        btn9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/off.gif"))); // NOI18N
        btn9.setText("J");
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });

        drivesGroup.add(btn10);
        btn10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/off.gif"))); // NOI18N
        btn10.setText("K");
        btn10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn10ActionPerformed(evt);
            }
        });

        drivesGroup.add(btn11);
        btn11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/off.gif"))); // NOI18N
        btn11.setText("L");
        btn11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn11ActionPerformed(evt);
            }
        });

        drivesGroup.add(btn12);
        btn12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/off.gif"))); // NOI18N
        btn12.setText("M");
        btn12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn12ActionPerformed(evt);
            }
        });

        drivesGroup.add(btn13);
        btn13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/off.gif"))); // NOI18N
        btn13.setText("N");
        btn13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn13ActionPerformed(evt);
            }
        });

        drivesGroup.add(btn14);
        btn14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/off.gif"))); // NOI18N
        btn14.setText("O");
        btn14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn14ActionPerformed(evt);
            }
        });

        drivesGroup.add(btn15);
        btn15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/off.gif"))); // NOI18N
        btn15.setText("P");
        btn15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn15ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btn8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn0, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn7))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn15)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn0)
                    .addComponent(btn1)
                    .addComponent(btn2)
                    .addComponent(btn3)
                    .addComponent(btn4)
                    .addComponent(btn5)
                    .addComponent(btn6)
                    .addComponent(btn7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn8)
                    .addComponent(btn9)
                    .addComponent(btn10)
                    .addComponent(btn11)
                    .addComponent(btn12)
                    .addComponent(btn13)
                    .addComponent(btn14)
                    .addComponent(btn15))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        driveInfoPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Drive info"));

        jLabel1.setFont(jLabel1.getFont());
        jLabel1.setText("Track:");

        lblSector.setFont(lblSector.getFont().deriveFont(lblSector.getFont().getStyle() | java.awt.Font.BOLD));
        lblSector.setText("0");

        jLabel3.setFont(jLabel3.getFont());
        jLabel3.setText("Sector:");

        jLabel4.setFont(jLabel4.getFont());
        jLabel4.setText("Head:");

        jLabel5.setFont(jLabel5.getFont());
        jLabel5.setText("Offset:");

        lblTrack.setFont(lblTrack.getFont().deriveFont(lblTrack.getFont().getStyle() | java.awt.Font.BOLD));
        lblTrack.setText("0");

        lblHead.setFont(lblHead.getFont().deriveFont(lblHead.getFont().getStyle() | java.awt.Font.BOLD));
        lblHead.setText("unloaded");

        lblOffset.setFont(lblOffset.getFont().deriveFont(lblOffset.getFont().getStyle() | java.awt.Font.BOLD));
        lblOffset.setText("0");

        javax.swing.GroupLayout driveInfoPanelLayout = new javax.swing.GroupLayout(driveInfoPanel);
        driveInfoPanel.setLayout(driveInfoPanelLayout);
        driveInfoPanelLayout.setHorizontalGroup(
            driveInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(driveInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(driveInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(driveInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(driveInfoPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblOffset))
                    .addComponent(lblSector)
                    .addComponent(lblHead)
                    .addComponent(lblTrack))
                .addContainerGap(220, Short.MAX_VALUE))
        );
        driveInfoPanelLayout.setVerticalGroup(
            driveInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(driveInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(driveInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblHead))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(driveInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(lblTrack))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(driveInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblSector))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(driveInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(lblOffset))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout runtimePanelLayout = new javax.swing.GroupLayout(runtimePanel);
        runtimePanel.setLayout(runtimePanelLayout);
        runtimePanelLayout.setHorizontalGroup(
            runtimePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, runtimePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(runtimePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(driveInfoPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        runtimePanelLayout.setVerticalGroup(
            runtimePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(runtimePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(driveInfoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Run-time", runtimePanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void umountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_umountButtonActionPerformed
        int i = driveCombo.getSelectedIndex();
        ((Drive)drives.get(i)).umount();
        updateGUI(i);
    }//GEN-LAST:event_umountButtonActionPerformed

    private void mountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mountButtonActionPerformed
        int i = driveCombo.getSelectedIndex();
        try { ((Drive) drives.get(i)).mount(txtImage.getText()); } catch (IOException ex) {
            DiskImpl.showErrorMessage(ex.getMessage());
            txtImage.grabFocus();
        }
        updateGUI(i);
    }//GEN-LAST:event_mountButtonActionPerformed

    private void browseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseButtonActionPerformed
        JFileChooser f = new JFileChooser();
        ImageFilter f1 = new ImageFilter();
        ImageFilter f2 = new ImageFilter();
        
        f1.addExtension("dsk");
        f1.addExtension("bin");
        f1.setDescription("Image files (*.dsk, *.bin)");
        f2.addExtension("*");
        f2.setDescription("All files (*.*)");
        
        f.setDialogTitle("Open an image");
        f.setAcceptAllFileFilterUsed(false);
        f.addChoosableFileFilter(f1);
        f.addChoosableFileFilter(f2);
        f.setFileFilter(f1);
        f.setApproveButtonText("Open");
        int i = driveCombo.getSelectedIndex();
        File ff = ((Drive)drives.get(i)).getImageFile();
        f.setSelectedFile(ff);
        int returnVal = f.showOpenDialog(this);
        f.setVisible(true);
        if(returnVal == JFileChooser.APPROVE_OPTION)
            txtImage.setText(f.getSelectedFile().getAbsolutePath());
    }//GEN-LAST:event_browseButtonActionPerformed

    private void txtImageInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txtImageInputMethodTextChanged
        if (txtImage.getText().equals("")) mountButton.setEnabled(false);
        else mountButton.setEnabled(true);
    }//GEN-LAST:event_txtImageInputMethodTextChanged

    private void driveComboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_driveComboItemStateChanged
        int i = driveCombo.getSelectedIndex();
        updateGUI(i);
    }//GEN-LAST:event_driveComboItemStateChanged

    private void createButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createButtonActionPerformed
        JFileChooser f = new JFileChooser();
        ImageFilter f1 = new ImageFilter();
        ImageFilter f2 = new ImageFilter();
        
        f1.addExtension("dsk");
        f1.addExtension("bin");
        f1.setDescription("Image files (*.dsk, *.bin)");
        f2.addExtension("*");
        f2.setDescription("All files (*.*)");
        
        f.setDialogTitle("Create new image");
        f.setAcceptAllFileFilterUsed(false);
        f.addChoosableFileFilter(f1);
        f.addChoosableFileFilter(f2);
        f.setFileFilter(f1);
        f.setApproveButtonText("Save");
        f.setSelectedFile(null);
        int returnVal = f.showSaveDialog(this);
        f.setVisible(true);
        if(returnVal == JFileChooser.APPROVE_OPTION)
            try {
                Drive.createNewImage(f.getSelectedFile().getAbsolutePath());
            } catch(IOException e) {
                DiskImpl.showErrorMessage("Couldn't create an image file");
            }
    }//GEN-LAST:event_createButtonActionPerformed

    private void btn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn0ActionPerformed
        driveInfoIndex = 0;
        updateDriveInfo();
    }//GEN-LAST:event_btn0ActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        driveInfoIndex = 1;
        updateDriveInfo();
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        driveInfoIndex = 2;
        updateDriveInfo();
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        driveInfoIndex = 3;
        updateDriveInfo();
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        driveInfoIndex = 4;
        updateDriveInfo();
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        driveInfoIndex = 5;
        updateDriveInfo();
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        driveInfoIndex = 6;
        updateDriveInfo();
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        driveInfoIndex = 7;
        updateDriveInfo();
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        driveInfoIndex = 8;
        updateDriveInfo();
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        driveInfoIndex = 9;
        updateDriveInfo();
    }//GEN-LAST:event_btn9ActionPerformed

    private void btn10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn10ActionPerformed
        driveInfoIndex = 10;
        updateDriveInfo();
    }//GEN-LAST:event_btn10ActionPerformed

    private void btn11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn11ActionPerformed
        driveInfoIndex = 11;
        updateDriveInfo();
    }//GEN-LAST:event_btn11ActionPerformed

    private void btn12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn12ActionPerformed
        driveInfoIndex = 12;
        updateDriveInfo();
    }//GEN-LAST:event_btn12ActionPerformed

    private void btn13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn13ActionPerformed
        driveInfoIndex = 13;
        updateDriveInfo();
    }//GEN-LAST:event_btn13ActionPerformed

    private void btn14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn14ActionPerformed
        driveInfoIndex = 14;
        updateDriveInfo();
    }//GEN-LAST:event_btn14ActionPerformed

    private void btn15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn15ActionPerformed
        driveInfoIndex = 15;
        updateDriveInfo();
    }//GEN-LAST:event_btn15ActionPerformed

    private void alwaysCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alwaysCheckActionPerformed
        this.setAlwaysOnTop(alwaysCheck.isSelected());
}//GEN-LAST:event_alwaysCheckActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox alwaysCheck;
    private javax.swing.JButton browseButton;
    private javax.swing.JToggleButton btn0;
    private javax.swing.JToggleButton btn1;
    private javax.swing.JToggleButton btn10;
    private javax.swing.JToggleButton btn11;
    private javax.swing.JToggleButton btn12;
    private javax.swing.JToggleButton btn13;
    private javax.swing.JToggleButton btn14;
    private javax.swing.JToggleButton btn15;
    private javax.swing.JToggleButton btn2;
    private javax.swing.JToggleButton btn3;
    private javax.swing.JToggleButton btn4;
    private javax.swing.JToggleButton btn5;
    private javax.swing.JToggleButton btn6;
    private javax.swing.JToggleButton btn7;
    private javax.swing.JToggleButton btn8;
    private javax.swing.JToggleButton btn9;
    private javax.swing.JPanel configPanel;
    private javax.swing.JButton createButton;
    private javax.swing.JComboBox driveCombo;
    private javax.swing.JPanel driveInfoPanel;
    private javax.swing.ButtonGroup drivesGroup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblHead;
    private javax.swing.JLabel lblOffset;
    private javax.swing.JLabel lblSector;
    private javax.swing.JLabel lblTrack;
    private javax.swing.JButton mountButton;
    private javax.swing.JPanel runtimePanel;
    private javax.swing.JTextField txtImage;
    private javax.swing.JButton umountButton;
    // End of variables declaration//GEN-END:variables
    
}
