== Writing a compiler

This tutorial will guide you to how to create a compiler for emuStudio. It focuses on things around
emuStudio, emuLib and some common practices. It will not dig deep into the compiler theory, only what will be required
on the way.

In present days, general scheme of compiler's work is parsing, semantic analysis, optimalization and code generation.
Quite tedious and error-prone work of parsing can be generated automatically with parser generators. All emuStudio
compilers use such tools; and they will be also used in this tutorial:

- http://jflex.de/[JFlex] for generating the lexical analyzer, or lexer for short,
- http://www2.cs.tum.edu/projects/cup/[Java cup] for generating LR(k) parsers.

Before reading on, please read the <<INTRODUCTION_PLUGINS>> chapter. It provides the information
needed for setting up the development environment and explains how emuStudio plug-ins' lifecycle work.

[[COMPILER_GETTING_STARTED]]
=== Getting started

In the context of the whole emulator, the compiler is usually an assembler which produces binary instructions for
the emulated CPU. However, it does not have to be assembler; it really can be any language compiler. The output of
the compiler is often loaded directly into emulated operating memory, so the program can be run in emuStudio in a
single click. This is one of the great features of emuStudio.

A compiler is a plug-in, which means that it requires to implement an API. The API for compilers is defined in the form
of Java interfaces and some classes in emuLib, in package `emulib.plugins.compiler`. This tutorial will guide
you with implementing the API and the whole compiler.

[[COMPILER_SSEM_ASM]]
=== Assembler for SSEM

In this tutorial, we will implement an assembler for the world's very first stored-program computer,
https://en.wikipedia.org/wiki/Manchester_Small-Scale_Experimental_Machine[SSEM], nicknamed "Baby". It was a predecessor
of Manchester Mark 1 which led to Ferranti Mark 1, the world's first commercially available general-purpose computer.

It it very simple computer, which can run only 7 instructions. The instructions table
follows (modified from https://en.wikipedia.org/wiki/Manchester_Small-Scale_Experimental_Machine#Programming[Wikipedia]):

[cols=">2m,<m,<5%m,<20%",frame="topbot",options="header,footer"]
|===================================================================
|Binary code |Mnemonic        |Action            |Operation
|000         |JMP S           | S(L) -> CI       |Jump to the instruction at the address obtained from the specified memory
                                                  address `S(L)` (absolute unconditional jump)
|100         |JRP / JPR / JMR S | CI + S(L) -> CI |Jump to the instruction at the program counter (`CI`) plus the
                                                  relative value obtained from the specified memory address `S(L)`
                                                  (relative unconditional jump)
|010         |LDN S           |-S(L) -> A       |Take the number from the specified memory address `S(L)`, negate it,
                                                  and load it into the accumulator
|110         |STO S           |A -> S(L)        |Store the number in the accumulator to the specified memory address `S(L)`
|001 or 101  |SUB S           |A - S(L) -> A    |Subtract the number at the specified memory address `S(L)` from the
                                                  value in accumulator, and store the result in the accumulator
|011         |CMP / SKN       |if A<0 then CI+1->CI |Skip next instruction if the accumulator contains a negative value
|111         |STP  / HLT      |Stop              |
|===================================================================

The instructions are stored in a memory, which had 32 cells. Each cell was 32 bits long, and each instruction fit into
exactly one cell. So each instruction has 32 bits. The bit representation was reversed, so the most and the least
significant bits were put on opposite sides. For example, value `3`, in common personal computers represented as `011`,
was in SSEM represented as `110`.

The instruction format is as follows:

[width="50%",cols=">2s,<m,<m,<m,<m,<m,<m,<m,<m,<m,<m,<m",frame="topbot",options="footer"]
.SSEM Instruction Format
|===================================================================
| Bit:  | 00  | 01 | 02 | 03 | 04 | ... | 13 | 14 | 15 | ... | 31
| Use:  | L   | L  | L  | L  | L  |  0  | I  | I  | I  | 0   | 0
| Value:| 2^0 |    |    |    |    |     |    |    |    |     | 2^31
|===================================================================

where bits `LLLLL` denote a "line", which is basically the memory address - index of a memory cell. It can be understood
as instruction operand. Bits `III` specify the instruction opcode (3 bits are enough for 7 instructions).

=== Language specification

Each compiler is just a program which translates an input source code into output code. Usually, the input language is
more high level than the output language, and often offers some features, which are not supported by the output language.
For example, assembler source codes often support comments, various formats of number literals, labels, or macros. These
are features, which are not supported by the instruction set itself, and they must be translated to it by compiler.

SSEM assembler specification can be started with informal expressing, what it will know:

[[COMPILER_TOKEN_CATEGORIES]]
==== Token categories

Tokens, parsed by lexical analyzer have assigned a so-called category. The category is useful mainly for syntax
highlighter in emuStudio editor. For example, reserved words are colored differently than e.g. numeric constants, or
comments.

The list of all categories can be seen in the following class:
https://github.com/vbmacher/emuLib/blob/branch-9_0/src/main/java/emulib/plugins/compiler/Token.java[Token.java].


==== New-lines

New-line character (LF, CR, or CRLF) will be required as a delimiter of instructions, and as the last character.
Successive empty new-line characters will be ignored.

==== Instructions

Assembler will support all forms of instructions shown in the table in section <<COMPILER_SSEM_ASM>>. All instructions must
start with a line number. For example:

    01 LDN 20

Instructions belong to token category called "reserved words".

==== Literals / constants

Raw number constants can be defined in separate lines using special preprocessor keywords. The first one is `NUM xxx`,
where `xxx` is a number in either decimal or hexadecimal form. Hexadecimal format must start with prefix `0x`. For example:

    00 NUM 0x20
    01 NUM 1207943145

Another keyword is `BNUM xxx`, where `xxx` can be only a binary number. For example:

    01 BNUM 10011011111000101111110000111111

It means that the number will be stored untouched to the memory in the format as it appears in the binary form.

There exists also a third keyword, `BINS xxx`, with the exact meaning as `BNUM`. The reason for its presence is to
be compatible with most of the programs http://www.cs.ubc.ca/~hilpert/e/SSEM/programs/noodle.html[found on internet].

For all constants, the following rules hold. Only integral constants are supported, and the allowed range is from 0 - 31
(maximum is 2^5).

Word `NUM`, `BNUM` and `BINS` keywords belong to "preprocessor" category, but number constants to the category called
"literals".

==== Comments

Only one-line comments will be supported, but of various forms. Generally, comment will be everything starting with
some prefix until the end of the line. Comment prefixes are:

- double-slash (`//`)
- semi-colon (`;`)
- double-dash (`--`)

The token category of comments is "comments".

==== Full example

For example, simple `5+3` addition can be implemented as follows:

    0 LDN 7 // load negative X into the accumulator
    1 SUB 8 // subtract Y from the value in the accumulator
    2 STO 9 // store the sum at address 7
    3 LDN 9 // A = -(-Sum)
    4 STO 9 // store sum
    5 HLT

    7 NUM 3 // X
    8 NUM 5 // Y
    9       // here will be the result

The accumulator should now contain value `8`, as well as memory cell at index 9.

=== Preparing the environment

In order to start developing the compiler, create new Java project in your favorite IDE. In emuStudio, Maven is used for
dependencies management. If you're not familiar with Maven, you can start
https://maven.apache.org/guides/getting-started/maven-in-five-minutes.html[here].

The compiler will be implemented as another standard emuStudio plug-in in standard path
`plugins/compilers/as-ssem`. It will inherit all Maven plug-in dependencies from the main POM file.

The directory structure is "dictated" by Maven, so it should look as follows:

    src/
      main/
        java/
        resources/
    test/
      java/
    pom.xml

NOTE: Note the naming of the plug-in. We are following the naming convention as described in the <<INTRODUCTION_NAMING>>
      guide.

The POM file of the project looks as follows:

[source,xml]
.`pom.xml`
----
include::../../../plugins/compilers/as-ssem/pom.xml[]
----

=== Lexer and parser

==== Lexical analyzer (lexer)

We will start with definition of the lexer specfile. It is a special file, which will be given to http://jflex.de/[JFlex]
during project compilation. Jflex will generate a Java class - the lexer - which will be used by the parser later, and
by emuStudio editor, too. The specification file has special place in the directory structure:

    src/
      main/
        jflex/
          lexer.jflex

NOTE: Note that the specfile is not put into resources directory. If it was so, then it would be included in the final
      JAR file.


JFlex will be called during compilation of the assembler by the
http://jflex.sourceforge.net/maven-jflex-plugin/generate-mojo.html[JFlex Maven plugin] (see the POM file above).
The content of the specfile is as follows:

[source,flex]
.`src/main/jflex/ssem.jflex`
----
include::../../../plugins/compilers/as-ssem/src/main/jflex/lexer.jflex[lines=20..-1]
----

As you can notice, the specfile uses special class named `TokenImpl`. We must implement this class by ourselves. It
holds the basic information about the parsed token, like offset, length, type, etc. There are several requirements
when implementing the class:

- It must extend `java_cup.runtime.Symbol` class, for JFlex - cup interoperability.
- It must implement `emulib.plugins.compiler.Token` interface, for being able to use this class in emuStudio syntax
  highlighter
- It's now a secret, but it would have to implement also special `Symbols` interface, which will be generated by
  parser, described in section below.

Syntax highlighter in emuStudio represents the source code in a dynamic "lexical tree". It scans regularly required text
blocks in the editor and translates them into the symbolic representation - into tokens, which are arranged in a tree
structure. Tokens are parsed by the lexer, provided by us. And `Token` interface is the shared API known by our specific
lexer and general syntax highlighter in emuStudio.

Tokens are assigned into categories, as was already mentioned in section <<COMPILER_TOKEN_CATEGORIES>>. Token categories have
assigned their specific editor style, like color or font.

The content of the `net.sf.emustudio.ssem.assembler.TokenImpl` class is as follows:

[source,java]
.`src/main/java/net/sf/emustudio/ssem/assembler/TokenImpl.java`
----
include::../../../plugins/compilers/as-ssem/src/main/java/net/sf/emustudio/ssem/assembler/TokenImpl.java[lines=20..-1]
----

[[COMPILER_GRAMMAR]]
==== Syntax analyzer (parser)

Next, we define the grammar file. It is also a special file, which will be given to cup during project
compilation. Cup will generate Java classes - the parser - which we will use in our code. The specfile
has special place in the directory structure:

    src/
      main/
        cup/
          parser.cup

Grammar type and form we use depends on the parsing algorithm we choose. In emuStudio, all compilers use
http://www2.cs.tum.edu/projects/cup/[Java cup] parser generator, which does bottom-up parsing, and supported grammars
are of type LALR.

The main difference between LL and LALR grammars is that in LALR you can freely use left-recursion, but not right
recursion. Otherwise you would get shift/reduce conflicts. For more information, see for example
https://lambda.uta.edu/cse5317/notes/node21.html[this site].

The grammar specfile of SSEM assembler parser follows:

[source]
.`src/main/cup/parser.cup`
----
include::../../../plugins/compilers/as-ssem/src/main/cup/parser.cup[lines=20..-1]
----

The right sides - code snippets wrapped between `{:` and `:}` - is Java code which will be executed when particular rule
of the grammar is applied. Remember, that they will be applied in reverse - first will be applied the right-most rules.

There exist a special variable `RESULT`, which should return some Java object of type which the
non-terminal defines for it footnote:[For example, `non terminal Instruction Statement;` in the gramamr above defines a
non-terminal `Statement`, which should return an instance of `Instruction` class. The class `Instruction` must be
implemented manually - it is part of AST; there are no special requirements for the implementation.].

For more information, especially about the `error` symbol, please read http://www2.cs.tum.edu/projects/cup/[cup]
documentation.

[[COMPILER_AST]]
==== Introducing AST

The code won't compile so far. The reason is that the parser strangely uses some undefined classes, such as `Program`,
`ASTnode`, `Instruction` and `Constant`. They are defined in the grammar file as follows (see above):

    non terminal Program Program;
    non terminal ASTnode Statement;
    non terminal Instruction Instruction;
    non terminal Constant Constant;

These classes are part of so-called abstract syntax tree, and they wait for our implementation. Abstract Syntax Tree
(or AST) is a "symbolic" representation of the parsed program source code. The parser creates one as a side-effect of
parsing. It is different from Parse Syntax Tree (PST), which represents a tree of true grammar derivations which were
"detected" by the parser for given source code of a program.

AST is something more artificial, ie. not all grammar rules need to be taken into account when representing the program.
For this reason, we define only some "nodes" of the derivation tree. In our case, it is `Program`, representing the
"root" of the tree, which has children - `Statement`s. Statements have `Instruction`s or `Constant`s as its children.

Do you remember those code snippets in the grammar specfile wrapped in `{: ... :}` ? This code snippets create the
AST, just follow them.

It's now time to implement them. Since we know all nodes are just nodes of our AST, we should define common `ASTnode`
interface first:

[source, java]
.`src/main/java/net/sf/emustudio/ssem/assembler/tree/ASTnode.java`
----
include::../../../plugins/compilers/as-ssem/src/main/java/net/sf/emustudio/ssem/assembler/tree/ASTnode.java[lines=20..-1]
----

This interface will be useful when we will traverse the tree. For tree traversal it is very well-suited the
https://sourcemaking.com/design_patterns/visitor[Visitor pattern]. The idea of traversing a tree using visitor pattern
is to have the "visitor" object - which represents an object which wants to go through all nodes of the tree and do
something. The algorithm of visiting is based on a premise that each node of the AST implements the `accept()` method.
That way, each node is responsible for calling the visitor for each its children and itself.
So the effect is that the "visitor" will "get" the all tree node objects, when the `accept()` method is called on the
root of the tree.

We can now define the visitor interface as follows:

[source, java]
.`src/main/java/net/sf/emustudio/ssem/assembler/tree/ASTvisitor.java`
----
include::../../../plugins/compilers/as-ssem/src/main/java/net/sf/emustudio/ssem/assembler/tree/ASTvisitor.java[lines=20..-1]
----

The methods of the visitor will be implemented by some visitor, for example a code generator. However, we need to
finish implementation of the AST first.

===== 'Program' node

The root node of the AST is the `Program` class. According to the grammar, it contains all the statements, which are
either `Instruction` or `Constant`. Notice how we implemented traversing of the node:

[source, java]
.`src/main/java/net/sf/emustudio/ssem/assembler/tree/Program.java`
----
include::../../../plugins/compilers/as-ssem/src/main/java/net/sf/emustudio/ssem/assembler/tree/Program.java[lines=20..-1]
----

The important note is that how the statements are stored. They are in fact the children of the program node. For this
purpose a key-value map is used. Key has type `Integer` and it represents the line - or memory cell index, or address -
on which the statement will be located. That way we can write several instructions which lie on the same line, e.g.:

    01 LDN 15
    01 STO 06

which will be translated into two statements, but the program node will contain just the last one. The reason is that
they share the line - `01` - which is the key in the map of statements, so the first statement will be "overwritten"
by the second one.

It is for a debate if we want this behavior to happen. For simplicity, we allow it. Otherwise we would throw some
compiler exception.

===== 'Instruction' node

Instruction node represents the instruction. If you remember, each instruction except `STP` and `CMP` has a parameter,
or better - operand - which is a "line" - index of a memory cell. It would be possible to represent specific
instructions by separate classes, but since the required operations would be shared, it would be much easier to have
just one class for all the instructions. Generally, instructions with same number and type of parameters are usually
implemented in one AST node.

Here's the source code:

[source,java]
.`src/main/java/net/sf/emustudio/ssem/assembler/tree/Instruction.java`
----
include::../../../plugins/compilers/as-ssem/src/main/java/net/sf/emustudio/ssem/assembler/tree/Instruction.java[lines=20..-1]
----

Note that the constructor is private. The implication is that it is just impossible to create some invalid `Instruction`
object. The only possible way how to define it is using static factory methods, which represent the instructions
themselves. These are called from the parser - check the grammar specfile in the section <<COMPILER_GRAMMAR>>.

Also, note that we can compare instructions based on opcode and operand. This is allowed by custom implementations of
methods `hashCode()` and `equals()`.

===== 'Constant' node

Another kind of statement is a constant. The constant is just a number, and the node class is very simple:

[source,java]
----
include::../../../plugins/compilers/as-ssem/src/main/java/net/sf/emustudio/ssem/assembler/tree/Constant.java[lines=20..-1]
----

Comparing `Constant` instances is based on comparing the numbers they represent.

==== Testing

It is very good practice to write automated tests. These will give us some level of confidence that what we did so far
is actually working. It is the earliest feedback we can get on our work, which consequently improves the speed of
creating sofware which actually works.

A unit test is just a normal class which contains test methods. A test method generally creates the testing object, does
the testing operation and finally check if the operation did what it should. Each test method should test just one thing
and should be short and clear. It is good practice to name test method according to the test case, possibly resulting
in a whole sentence, in camel case.

Java projects use some unit testing framework for that, e.g. JUnit or TestNG, which recognizes those classes
automatically and runs the test methods during the compilation of the project. If a test fails, the whole compilation
is stopped as failed.

For lexer and parser we create unit test classes, which will be placed here (following to Maven directory structure):

    src/
      test/
        java/
          net/
            sf/
              emustudio/
                ssem/
                  assembler/
                    LexerTest.java
                    ParserTest.java

The content of the test classes are as follows:

[source,java]
.`src/test/java/net/sf/emustudio/ssem/assembler/LexerTest.java`
----
include::../../../plugins/compilers/as-ssem/src/test/java/net/sf/emustudio/ssem/assembler/LexerTest.java[lines=20..-1]
----

[source,java]
.`src/test/java/net/sf/emustudio/ssem/assembler/ParserTest.java`
----
include::../../../plugins/compilers/as-ssem/src/test/java/net/sf/emustudio/ssem/assembler/ParserTest.java[lines=20..-1]
----

NOTE: The tests of parser are based on comparing `Instruction` and `Constant` instances with JUnit's `assertEquals()`
      method. This is possible only because of overriden `equals()` and `hashCode()` methods in the classes, since
      they are used directly by Java when it is comparing the instances.

=== The main class

The time has come for implementing the main plug-in class. It will be placed in a package
`net.sf.emustudio.ssem.assembler`, and the class will be named `CompilerImpl`.

There are several requirements (behavioral contracts) put on the compiler main class:

- It must implement `emulib.plugins.compiler.Compiler` interface. There already exists helper abstract class called
  `emulib.plugins.compiler.AbstractCompiler`, which implements some fundamental and general methods. We will use that
  class.
- It must be annotated with `emulib.annotations.PluginType` annotation.
- The constructor gets two arguments: unique plugin ID (`Long`) and `emulib.runtime.ContextPool` object. Both values
  are created by emuStudio, and we will talk about them later.

Now, the "skeleton" of the class follows:

[source,java]
.`src/main/java/net/sf/emustudio/ssem/assembler/CompilerImpl.java`
----
package net.sf.emustudio.ssem.assembler;

import emulib.annotations.PLUGIN_TYPE;
import emulib.annotations.PluginType;
import emulib.plugins.compiler.AbstractCompiler;
import emulib.plugins.compiler.LexicalAnalyzer;
import emulib.plugins.compiler.SourceFileExtension;
import emulib.runtime.ContextPool;

import java.io.IOException;
import java.io.Reader;
import java.util.Objects;

@PluginType(
    type = PLUGIN_TYPE.COMPILER,
    title = "SSEM Assembler",
    copyright = "\u00A9 Copyright 2016, YourName",
    description = "Assembler of SSEM processor language"
)
public class CompilerImpl extends AbstractCompiler {
    private static final SourceFileExtension[] SOURCE_FILE_EXTENSIONS = new SourceFileExtension[]{
        new SourceFileExtension("ssem", "SSEM source file")
    };
    private final ContextPool contextPool;

    public CompilerImpl(Long pluginID, ContextPool contextPool) {
        super(pluginID);
        this.contextPool = Objects.requireNonNull(contextPool);
    }

    @Override
    public boolean compile(String inputFileName, String outputFileName) {
        // TODO !!
        return false;
    }

    @Override
    public boolean compile(String inputFileName) {
        String outputFileName = Objects.requireNonNull(inputFileName);
        SourceFileExtension srcExtension = SOURCE_FILE_EXTENSIONS[0];

        int i = inputFileName.lastIndexOf("." + srcExtension.getExtension());
        if (i >= 0) {
            outputFileName = outputFileName.substring(0, i);
        }
        return compile(inputFileName, outputFileName + ".bin");
    }

    @Override
    public LexicalAnalyzer getLexer(Reader reader) {
        return new LexerImpl(reader);
    }

    @Override
    public SourceFileExtension[] getSourceSuffixList() {
        return SOURCE_FILE_EXTENSIONS;
    }

    @Override
    public void destroy() {

    }

    @Override
    public void showSettings() {

    }

    @Override
    public boolean isShowSettingsSupported() {
        return false;
    }

    @Override
    public String getVersion() {
        return "1.0";
    }
}
----

Some things are obvious, some maybe not. For example, method `getLexer()` is called by emuStudio for the syntax
highlighter. It is very straightforward - just return new `LexerImpl()` which was generated by JFlex from our
specfile.

Method `compile(String)` might seem complex at first look. It is "ugly" Java code which tries to check if the given
file name ends with our supported file suffix, which is ".ssem". We chose it as the suffix of SSEM source code file.
We could chose ".asm" or other extension as well. Then, the "real" `compile()` method is called with the input file
and the output file name, which has suffix ".bin".

Method `getSourceSuffixList()` returns all supported extensions, and will be used in the file filter in the open file
dialog shown in emuStudio.

Compiler can have it's own settings dialog (GUI window) which can be shown. This is reflected by the methods
`isShowSettingsSupported()` and `showSettings()`. Our assembler will not support the dialog.

The "real" `compile()` method is left to be done in the last section.

=== Generating code

So far, we have implemented a parser which creates our AST. Next operations which compilers do are semantic analysis,
optimization and code generation. These three phases are performed on the AST. The algorithms traverse the tree and
update some own internal state, or state of the AST based on visited nodes. Code generator at the end take the results,
and again - by traversing AST - generates the code.

In our case, we don't need any semantic analysis, like type-checks or so, because we have simple machine instructions,
which do not require it. We could optimize them, but for the simplicity we will omit this step as well. We will rather
focus on the final step - code generation.

You might remember the section <<COMPILER_AST>>, which talked about AST traversal. We already have `ASTnode` and `ASTvisitor`
interfaces. The traversal is already implemented, according to the Visitor pattern, by the nodes themselves. One thing
which is left to do is to implement the visitor itself - the code generator class.

For each encountered instruction, the code generator will generate a binary code. Our code generator will write the
binary representation into a file. However, it is generally better if I/O classes work with I/O abstractions
(streams, channels, etc.) rather than specific objects, e.g. files. Out code generator will be implemented in a
similar fashion. The code is as follows:

[source,java]
.`src/main/java/net/sf/emustudio/ssem/assembler/CodeGenerator.java`
----
include::../../../plugins/compilers/as-ssem/src/main/java/net/sf/emustudio/ssem/assembler/CodeGenerator.java[lines=20..-1]
----

There are several things to notice:

- Output code is written into class `SeekableOutputStream`. Wi will define this class later.
- `CodeGenerator` is a visitor, which has separate methods for code generation of `Constant` and `Instruction`.
- `CodeGenerator` can be "closed" - so it handles closing of the writer (our `SeekableOutputStream`).
- generated code is binary

The code generation is not that complex. There is some complexity caused by a fact, that the binary representations
are reversed, when comparing to our present-time PCs/laptops.

The idea of generating code for instruction is to prepare 4 bytes, 32 bits, which are then written into the "writer"
as one `Integer`, which has also 32 bits. The instruction format is explained in section <<COMPILER_SSEM_ASM>>. First 5 bits from
the left represent the "line" - instruction operand. It must be reversed.
Then, bits 13,14,15 represent the instruction opcode. It does not have to be reversed here, since the instructions are
already encoded properly in the `Instruction` class. Last two bytes are just empty.

Code generation for constant is much easier - it's just retrieving the value and writing it in the reversed fashion as
`Integer`.

Code generator uses a "seekable" output stream, which allows to seek in the output. It is a separate class, which is
actually an abstract class, extending `OutputStream`. The reason is easier testing:

[source,java]
.`src/main/java/net/sf/emustudio/ssem/assembler/SeekableOutputStream.java`
----
include::../../../plugins/compilers/as-ssem/src/main/java/net/sf/emustudio/ssem/assembler/SeekableOutputStream.java[lines=20..-1]
----

and here's the implementation:

[source,java]
.`src/main/java/net/sf/emustudio/ssem/assembler/MemoryAndFileOutput.java`
----
include::../../../plugins/compilers/as-ssem/src/main/java/net/sf/emustudio/ssem/assembler/MemoryAndFileOutput.java[lines=20..-1]
----

The "seeking" capability is required, because, as you remember, it's possible to write something like this:

    06 STO 05
    05 LDN 06
    07 STP

It's not quite common, but it's possible.


==== Testing

As being our practice, we must test it.

[source,java]
.`src/test/java/net/sf/emustudio/ssem/assembler/CodeGeneratorTest.java`
----
include::../../../plugins/compilers/as-ssem/src/test/java/net/sf/emustudio/ssem/assembler/CodeGeneratorTest.java[lines=20..-1]
----

=== Finalizing

We're almost done now! What is missing so far is to finish implementation of the main `CompilerImpl.compile()`  method.
Let's begin with it first.

[source,java]
.`src/main/java/net/sf/emustudio/ssem/assembler/CompilerImpl.java`
----
public class CompilerImpl extends AbstractCompiler {

    ...

    @Override
    public boolean compile(String inputFileName, String outputFileName) {
        notifyCompileStart();

        int errorCode = 0;
        try (Reader reader = new FileReader(inputFileName)) {
            MemoryContext<Byte> memory = contextPool.getMemoryContext(pluginID, MemoryContext.class);

            try (CodeGenerator codeGenerator = new CodeGenerator(new MemoryAndFileOutput(outputFileName, memory))) {
                LexerImpl lexer = new LexerImpl(reader);
                ParserImpl parser = new ParserImpl(lexer, new ComplexSymbolFactory(), this);

                Program program = (Program) parser.parse().value;
                if (program == null) {
                    throw new Exception("Unexpected end of file");
                }
                if (parser.hasSyntaxErrors()) {
                    throw new Exception("One or more errors has been found, cannot continue.");
                }

                program.accept(codeGenerator);
                programStart = program.getStartLine() * 4;
                notifyInfo("Compile was successful. Output: " + outputFileName);
            }
        } catch (Exception e) {
            errorCode = 1;
            LOGGER.error("Compilation error.", e);
            notifyError("Compilation error.");

            return false;
        } finally {
            notifyCompileFinish(errorCode);
        }

        return true;
    }

    ...
}
----

As input, we have full path to the input file, and to the output file. It is good to use Java
https://docs.oracle.com/javase/tutorial/essential/exceptions/tryResourceClose.html[try-with-resources]
statement for opening the files. The same approach can be used for the code generator, because the class implements
`AutoCloseable` interface.

We want to notify emuStudio about compilation progress, as we have already done in the parser, when dealing with
parsing errors. For this purpose, `emulib.plugins.compiler.AbstractCompiler` class offers several methods:

- `notifyCompileStart()`, which will inform emuStudio that the compilation has started,
- `notifyCompileFinish(errorCode)` will inform emuStudio that the compilation has finished, with given error code. footnote:[The
  error code should be defined by you, developer, if you want. It is a convention used also in other compilers that
  specific error has assigned a unique number. In our compiler, we do not use it.]
- `notifyOnMessage()` - notifies emuStudio about some general message, it can be either error, info, warning.
- `notifyWarning()` - compiler warning
- `notifyError()` - compilation error
- `notifyInfo()` - informational message
