[[INTRODUCTION_PLUGINS]]
== Introduction

This guide shall help you, the developer, to write your own virtual computer for emuStudio. From now on, every time
a 'virtual computer' will be mentioned, it should be always understood as a computer emulator written for emuStudio, if
it won't be said otherwise.

=== What is emuStudio

From user's point of view, emuStudio can be understood as an *emulation platform*, because it can run various emulators
in the same environment. It has a simple IDE, debugger and other features like automatic emulation, which makes emuStudio
quite powerful.

From developer's point of view, it is also a *framework*, because it provides API and lifecycle management for virtual
computers. There are some contracts how things work, what developer can count with, and what is not defined. This
tutorial shall guide the developer through these waters, hopefully at the end there won't be any serious problems with
writing custom virtual computers.

==== Core technologies

During programming, there are some commonly used technologies, which are mandatory when relevant. These are the "core
technologies", which are listed in the following table:

.Core technologies used in emuStudio
|===
|Technology | Description | Relevance | Link

|Git
|Version control system
|All
|https://git-scm.com/

|Java 8 SE
|Main programming language
|All
|http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html

|Maven 3
|Build lifecycle management
|All
|https://maven.apache.org/download.cgi

|SLF4J
|Facade for logger implementation
|All
|http://www.slf4j.org/

|JFlex
|Lexical analyzer generator
|Compilers
|http://jflex.de/

|Java CUP
|LR parser generator
|Compilers
|http://www2.cs.tum.edu/projects/cup/

|Edigen
|Disassembler generator
|CPU
|https://github.com/sulir/edigen

|emuLib
|Plugin API and runtime library
|All
|https://github.com/vbmacher/emuLib

|JUnit
|Java unit testing framework
|All
|http://junit.org/

|EasyMock
|Mock library
|All
|http://easymock.org/

|Asciidoctor
|Documentation generator
|Documentation module
|http://asciidoctor.org/
|===

CAUTION: emuStudio uses Maven for the build lifecycle management. All dependencies and their versions are defined in
      the root `pom.xml` file. When you use a library or some technology which is listed there, please use the
      same version as it is used by emuStudio. You will avoid unexpected conflicts or behavior of your plug-ins.

==== License

emuStudio with all its modules, including emuLib, is a free software. It is released with GNU GPL 2 license.

=== Contributing

Anyone can contribute to emuStudio. The source code is available on GitHub, at https://github.com/vbmacher/emuStudio.
emuStudio repository contains the main module, plug-ins (predefined set of virtual computers), testing tools,
and CI (continuous integration) tools.

There are basically two options how you can contribute. Either you fix or enhance emuStudio itself (or plug-ins), or
you implement completely new computer which can be used with emuStudio. The latter does not really mean to contribute,
unless it is included in the original emuStudio repository.

However, adding new computers to standard emuStudio must be consulted with the author in advance. While I encourage
people writing their own computers, I assume they will be mostly students having only little experience
and/or fixed-time projects which will end when the student passes. This is perfectly fine, but those projects should
be rather kept in other places.

Also, in the future there might be something like a plug-in repository, and a user would download what he wants manually.
So far, it is not like that and it is too soon to consider this.

==== Git workflow

Since the whole project is using `git` as the version control system (VCS), it has many benefits used for specification
of a way how people can actually contribute.

emuStudio uses very simple branching model. Each version (previous or currently developed) has its own branch. For
example, version 0.39, which is currently developed has name `branch-0_39`. On GitHub the branch is marked as a default.

When a new release is out, new branch is created which becomes a new default (e.g. `branch-0_40`). Also, a tag is
created for marking the last release commit.

When contributing, always derive new branch for fixing the bug or adding a feature from the latest branch, with
the highest version. The reason is that only major releases exists so far, and maintenance of older versions is not
supported (fixes will appear in new version). The other branches exist just for easier checking between versions.

NOTE: In the future, the branching model can change. The name of development branch should be always the same, but
      so far it is like was said.

A sample git workflow is as follows:

At first, fork emuStudio on GitHub. Then:

```
git clone https://github.com/your_name/emuStudio.git
git checkout -b fix-issue-143 origin/branch-0_39

.. fixing/implementing ..

git commit -a -m '[#143] Super hot fix'
git push
```

After the push, create a pull request to original emuStudio repository

The pull request will be seen by the author, which will make a review and either approve (and merge), comment or
rejects the pull request (with explanation).

As you could notice, commits should be named with the issue number before the commit title, in square brackets, e.g.:

```
[#143] Super hot fix
```

GitHub then automatically links the commit with the issue (a comment appears). For more information, see
https://help.github.com/articles/using-pull-requests/.

=== What is a virtual computer

Generally, a real computer can be decomposed into some cooperating components (still high-level), like CPU, bus, memory,
or devices. It is not far different from how it is in emuStudio. The core concept of a virtual computer is inspired by
the https://en.wikipedia.org/wiki/Von_Neumann_architecture[von Neumann model]. The model defines three types of core
components: CPU (control unit and arithmetic-logic unit), memory, and input/output devices. In emuStudio,
the virtual computer includes also these components, but the possibilities of interconnection and cooperation are not
bound to hardware limits or philosophy.

Each component of a virtual computer is a separate plug-in written in Java. A virtual computer is then just a set of
cooperating plug-ins which are loaded and initialized by emuStudio. The selection of plugins is handled externally, by
the user of emuStudio. The plugins list is extended with information about plug-in interconnection, which is specific
for each computer. Then we have something which is called *abstract schema*. But as was said, abstract schemas are
prepared by user, not plug-in developer.

For more information about how to create such a schema, please read the user manual. The whole process of loading and
initializing the plug-ins into working emulator is completely handled by emuStudio. Developer must hold to some
contracts, and principles of good object-oriented design, which are enough for ensuring that everything will work as
expected.

The following schema defines all plug-in types and their possible interconnections, as it is currently in emuStudio.

[graphviz]
---------------------------------------------------------------------
graph virtual_computer {
  splines=true;
  sep="+25,125";
  overlap=scalexy;
  nodesep=1;
  ranksep=1;
  node [shape = rect];

  Compiler -- Device [headlabel="0..N", taillabel="0..1" , labeldistance=2.5];
  Compiler -- CPU [headlabel="0..1", taillabel="0..1" ];
  Compiler -- Memory [headlabel="0..1", taillabel="0..1" ];

  CPU -- Memory [headlabel="0..1", labeldistance=2.5, taillabel="0..1" ];
  CPU -- Device [headlabel="0..N", taillabel="0..1" ];

  Memory -- Device [headlabel="0..N", taillabel="0..1" ];
  Device -- Device [ label = "0..N" ];

  {rank=same; Compiler Memory};
  {rank=same; CPU Device};
}
---------------------------------------------------------------------

As you can see, there are no restrictions about which plug-in can "see" or cooperate with another plug-in. For example,
a compiler can access all computer components, including CPU, devices and memory.

TIP: Most probably a compiler would want to access memory, in which case it would be able to load a compiled program
     directly there. But the reason why the compiler is allowed to access also other components is that the compiled
     program can contain either some information about initial states, or initial data which are needed to be preloaded
     into other components before program can be started (for example, content of abstract tapes in the case of RAM
     machine).

=== Plug-in basics

Each plug-in is a separate Java module, usually single jar file, placed in the proper directory. As it is necessary
to place the plug-in to proper location (`compilers/`, `cpu/`, `mem/`, and `devices/`), dependencies of both emuStudio
and all plug-ins should be included in `lib/` directory. The reason is to help ensuring that versions of shared
dependencies across plug-ins themselves and across emuStudio must be the same within single emuStudio distribution.

In emuStudio, plug-in source codes are located in `plugins/` subdirectory, then separated by plug-in type. For example:

https://github.com/vbmacher/emuStudio/tree/branch-0_39/plugins

In order to contribute to an existing plug-in, you can find the plug-in in some subdirectory. If you want to add a
new plug-in which should exist in the default emuStudio distribution, you would create new plug-in in that place as well.

CAUTION: Standard or "default" plug-ins force to use Maven and you must follow the standard which will be defined later.
      Also, before making any design changes or new plug-in development, please contact the emuStudio author.

Usually, your plug-ins will not be the standard part of default emuStudio distribution. In that case, you are not forced
to use Maven or any other technology, except of emuStudio API, contracts and the limits which might exist when involving
unknown third party dependencies. Also, you can use your own code style if you like.

==== Plug-in API

The basic idea of the development of the plug-in is to implement an API of that specific plug-in. This is actually only
thing which is required.

Plug-in API is stored in emuLib library (see <<Core technologies>>), so each plug-in must have emuLib as dependency.
This and following guides will show you some examples of how to implement a plug-in. For deeper details of all available
API, it is recommended to check the Javadoc.

==== Third-party dependencies

Each plug-in can depend on third-party libraries. It is recommended way how to avoid code duplication and reinventing
a wheel. If a plug-in depend on some third-party library, it is required to put the class path to the Manifest file
of the plug-in.

What is not required, however, is to define some default dependencies (listed below). emuStudio uses custom class-loader
for loading plug-ins, which handles the default dependencies automatically.

[horizontal]
emuLib:: Plugin API and runtime library
slf4J:: Facade for logger implementation
logback:: Logger implementation, successor of log4j

These dependencies should not be present in plug-in manifest files, they will be automatically loaded with emuStudio.
Please see emuStudio main POM file to determine the library versions.

In order to use other third-party dependencies, they must be mentioned in Manifest. The recommended way is to put the
dependencies in `/lib` subdirectory, and define relative path in Manifest from the root directory of where the emuStudio
is installed. For example, here is a Manifest file for RAM compiler plug-in:

[source]
----
Manifest-Version: 1.0
Implementation-Title: RAM Compiler
Implementation-Version: 0.39-SNAPSHOT
Archiver-Version: Plexus Archiver
Built-By: vbmacher
Specification-Title: RAM Compiler
Implementation-Vendor-Id: net.sf.emustudio
Class-Path: mem/ram-mem.jar lib/java-cup-runtime-11b.jar
Created-By: Apache Maven 3.3.3
Build-Jdk: 1.8.0_65
Specification-Version: 0.39-SNAPSHOT
----

The plug-in uses two non-default dependencies: RAM memory plug-in, and java-cup library. The first one is a memory
plug-in for emuStudio, so it is placed in `mem/` subdirectory, but java-cup library is completely third-party, and
non-default. The recommended place for storing these kind of libraries is `lib/` subdirectory.

NOTE: Cyclic dependencies are also supported.

[[INTRODUCTION_BEHAVIORAL]]
=== Emulation lifecycle

emuStudio is also a framework, which not only defines the API, but also the whole life cycle of plug-ins. It has the
control of all emulation processes, including CPU and all virtual devices. It proactively loads, instantiates and
initializes plug-ins. That way a plug-in developer can safely focus only on what the plug-in should do in the first place.

Behavior contracts define rules and assumptions which plug-in developer must hold to. emuStudio is assuming that
plug-ins "behave good", and if it is true, everything should work as expected. By ignoring the behavioral contracts
the emuStudio behavior is undefined; it can possibly corrupt the emulation process or crash whole emuStudio.

The list of some categories of behavioral contracts include:

- order of operations being called by emuStudio (e.g. order of loading / initialization of plug-ins)
- rules of allowed / not allowed method calls in particular contexts
- specification of signature of constructors
- threading concerns
- other

The behavioral contracts are described in particular Javadoc for emuLib and all modules to which it may concern.
The Javadoc contains special note which starts with capital `CONTRACT:`. The contract is mainly in the form of
explanation which other methods should not be called, or how particular thing should be implemented.

==== Main class

Each plug-in must have exactly one "main class" in Java, which will be annotated with `emulib.annotations.PluginType`
annotation. This annotation provides several information, like:

- title of the plug-in
- copyright notice and description of the plug-in
- what type of the plug-in is (compiler, CPU, memory, device),
- what version of emuLib it supports

The class must also inherit from `emulib.plugins.Plugin` interface (not necessarily directly).

==== Loading and initialization

Setting up plug-ins is a two-phase process and it is done solely in emuStudio. emuStudio has custom class loader, into
which it loads all plug-ins (classes and resources) and "registers" them in JVM.

===== Phase 1 - Loading

The plug-ins are loaded as a one bunch of extracted JARs mixed together, in a newly created class loader. The class
loader is immutable so further modification of plug-in loading (e.g. adding another component at run-time) is not
possible.

Dependencies explicitly specified in manifest files are recognized and loaded as well. With this, plug-ins can depend
on each other. However, in case of circular dependency, plug-ins loadin will fail.

The result of this phase is that all plug-in classes are loaded in memory and all main-classes instantiated. Each plug-in
main class must have a constructor with exactly two arguments:

[source,java]
----
SamplePlugin(Long pluginId, ContextPool contextPool) {
    ...
}
----

The `ContextPool` can be used (in this phase) only for *registering* custom plug-in contexts, but not for their
obtaining. More information can be found in emuLib's Javadoc.

[[INTRODUCTION_INITIALIZATION]]
===== Phase 2 - Initialization

The initialization of plug-ins follows as the second phase. In this phase, plug-ins should ask from given `ContextPool`
in the previous phase of context(s) of other, already registered plug-ins.

The order in which plug-ins are initialized is:

1. Compiler
2. CPU
3. Memory
4. Devices in the order as they are defined in the virtual computer configuration file

When following this contract, it cannot happen that a plug-in will ask for context which is not registered.

[[INTRODUCTION_NAMING]]
=== Naming conventions

Plug-in names (jar file names) follow naming conventions. The names differ based on plug-in types. From the jar file
name it should be clear what plug-in we are talking about. Generally, the jar file should begin with some custom
abbreviation of the real world "model" optionally preceded with the manufacturer (e.g. intel-8080, lsi-adm-3A, etc.).
Then plug-in type follows, as it is shown in the following table:

.Naming conventions for plug-in jar files
|===
|Plug-in type |Naming convention |Example

|Compiler
|`<language_abbreviation>-compiler`, or `as-<language_abbreviation>` for assemblers
|`as-8080`, `brainc-compiler`

|CPU
|`<optional_manufacturer>-<model_abbreviation>-cpu`
|`8080-cpu`, `z80-cpu`

|Memory
|`<model_or_main_features_abbreviation>-mem`
|`standard-mem`, `ram-mem`

|Device
|`<optional_manufacturer>-<model_abbreviation>-<device_type>`
|`88-disk`, `adm3a-terminal`

|===

Plug-in names can contain digits, small and capital letters (regex: `[a-zA-Z0-9]+`). Capital letters shall be used only
for the following reasons:

- word separation (e.g. zilogZ80),
- acronyms (e.g. RAM, standing for "Random Access Machine")

NOTE: Using naming conventions for development of official plug-ins is a must; for custom projects it is highly
      recommended. emuStudio does not use the naming convention for searching for plugins.

=== Coding Style

Unified coding style is as important as being a team player. It is the commonly-accepted order, which puts the code
readability at the same level everywhere. It is as in a classical book - you don't usually see multiple writing styles
or text organizations throughout the book. It is written as by only one author, even if it has more. The same purpose
has the code style, because the reader is always just one.

I encourage you to read a book called Clean Code from Robert Martin. You can find there many inspiring thoughts and
ideas how to write the code in a clean way.

==== License information

Each file must start with a comment with the license information. Please read part "How to Apply These
Terms to Your New Programs" at link http://www.gnu.org/licenses/gpl.html.

==== Indentation

I consider this section as very important, so as there is lots of time consuming debates about the "indentation problem".
Therefore I "codify" this to 4 spaces.

=== Use Maven if you can

Maven is a standard for Java projects today. It helps with the build process and manages dependencies in satisfying
and reusable way.

Each official emuStudio module (artifact) is available in custom Maven repository, including emuLib. In order to be able
to use them from Maven, put the following code into your `pom.xml` file:

[source,xml]
----
<distributionManagement>
  <repository>
    <id>emustudio-repository</id>
    <name>emuStudio Repository</name>
    <url>sftp://web.sourceforge.net:/home/project-web/emustudio/htdocs/repository</url>
  </repository>
</distributionManagement>
----

NOTE: Development of official standard plug-ins require using Maven.

=== Documenting plug-ins

There are two types of documentation:

- user documentation
- developer's documentation (not javadoc)

For now, the way how it is done is to place all the documentation in the `doc/` submodule of emuStudio. Please see
the `README.md` file of that submodule for more information how to do it.

=== Incorporating a plug-in to emuStudio

The philosophy about releasing is to keep everything as automatic as possible. The main reason is that if it was manual,
it would take some time which can be spent on something better. Of course there will be always some manual steps, but
it is better to keep them minimal.

The submodule `release/` is used now to create emuStudio releases. It expects that emuStudio artifacts are either
installed in local Maven repository, or they will be downloaded from emuStudio repository.

The submodule uses `maven-assembly-plugin` is used, and `assembly.xml` file exists which describes which artifacts
and files should be placed in which directories.

The following artifacts can be included in the release:

- Plug-in artifact (JAR file)
- Plug-in examples
- New computer configuration (if applicable)

==== Plug-in artifact

The condition is ofcourse that the plug-in must be a submodule in the main emuStudio repository. As an example,
let's use plug-in `plugins/compilers/as-ssem`. The point is to edit `release/assembly.xml` file, find the dependency
set for compilers (look for the line `<outputDirectory>/compilers</outputDirectory>`) and add the plug-in in that
set:

----
    <dependencySet>
      <includes>
        ...
        <include>net.sf.emustudio:as-ssem</include>
      </includes>
      ...
      <outputDirectory>/compilers</outputDirectory>
    </dependencySet>
----

Similarly, for other types of plug-ins there exist corresponding sections which should be used.

==== Plug-in examples

Similarly as was said in the previous subsection, the file which should be edited is `release/assembly.xml`. Examples
section is located in the bottom part, in a `fileSet` section. Examples are usually bound with specific compiler - and
they are also physically placed.

NOTE: Compilation of compiler plug-ins does not create examples artifacts (maybe it should in the future). The assembly
      therefore points to relative path of the example files.

For example, example files for plug-in `as-8080` are stored in the following section:

----
    <fileSet>
      <directory>../plugins/compilers/as-8080/examples</directory>
      <directoryMode></directoryMode>
      <includes>
        <include>**/*.asm</include>
        <include>**/*.inc</include>
      </includes>
      <outputDirectory>/examples/as-8080</outputDirectory>
    </fileSet>
----

The subdirectories in target `examples/` directory are organized by compiler plug-in names, or machine names if
the examples are rather bound to the whole virtual computer (e.g. disk images, etc.). Examples for whole virtual
computers are usually not bound with specific plug-ins and should be placed directly in the `release/files/examples/`
directory.

All files in the `release/files` are automatically included in the release.

==== New computer configuration

All predefined computer configurations are placed in directory `release/files/config`. The only step needed to be
done here is to create a computer configuration file and place it there. The `maven-assembly-plugin` will take care
of it and the configuration will be included in the release automatically.

=== What to do next

What follows are tutorials for developing specific emuStudio plug-ins - compiler, CPU, memory or a device. Prepare
your fingers, you'll write some code. Let's start.
