/* SPDX-FileCopyrightText: 2006-2026 Peter Jakubčo
   SPDX-License-Identifier: GPL-3.0-or-later */

plugins {
  id 'java'
  id 'idea'
  id 'antlr'
  id 'com.adarshr.test-logger' version '4.0.0'
}

ext {
  moduleMainClass = 'net.emustudio.plugins.compiler.asZ80.Runner'
  antlrPackage = 'net.emustudio.plugins.compiler.asZ80'
}

dependencies {
  antlr libs.antlr
  implementation libs.antlrRuntime

  implementation libs.emuLib
  implementation libs.slf4JApi

  testImplementation libs.cpuTestSuite
  testImplementation libs.junit
  testImplementation libs.easyMock
  testImplementation libs.slf4JSimple
}

apply from: "$rootDir/gradle/conventions/antlr-compiler-conventions.gradle"
