/*
 * This file is part of emuStudio.
 *
 * Copyright (C) 2006-2020  Peter Jakubčo
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */
package net.emustudio.plugins.memory.standard.gui;

import net.emustudio.emulib.runtime.CannotUpdateSettingException;
import net.emustudio.emulib.runtime.PluginSettings;
import net.emustudio.emulib.runtime.helpers.RadixUtils;
import net.emustudio.emulib.runtime.interaction.Dialogs;
import net.emustudio.emulib.runtime.interaction.FileExtensionsFilter;
import net.emustudio.plugins.memory.standard.gui.model.FileImagesModel;
import net.emustudio.plugins.memory.standard.gui.model.ROMmodel;
import net.emustudio.plugins.memory.standard.gui.model.TableMemory;
import net.emustudio.plugins.memory.standard.MemoryContextImpl;
import net.emustudio.plugins.memory.standard.MemoryImpl;
import net.emustudio.plugins.memory.standard.RangeTree;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import javax.swing.*;
import java.nio.file.Path;
import java.util.Objects;
import java.util.Optional;

public class SettingsDialog extends javax.swing.JDialog {
    private final static Logger LOGGER = LoggerFactory.getLogger(SettingsDialog.class);

    private final MemoryContextImpl context;
    private final MemoryImpl memory;
    private final TableMemory tblMem;
    private final FileImagesModel imagesModel;
    private final ROMmodel romModel;
    private final Dialogs dialogs;

    public SettingsDialog(JDialog parent, MemoryImpl memory, MemoryContextImpl context, TableMemory tblMem,
                          PluginSettings settings, Dialogs dialogs) {
        super(parent, true);

        this.memory = Objects.requireNonNull(memory);
        this.context = Objects.requireNonNull(context);
        this.tblMem = Objects.requireNonNull(tblMem);
        this.dialogs = Objects.requireNonNull(dialogs);

        initComponents();
        super.setLocationRelativeTo(parent);

        loadSettings(settings);

        imagesModel = new FileImagesModel(settings, dialogs);
        tblImages.setModel(imagesModel);

        this.romModel = new ROMmodel(this.context);
        tblROM.setModel(romModel);
    }

    private void loadSettings(PluginSettings settings) {
        try {
            txtBanksCount.setText(String.valueOf(settings.getInt("banksCount", 0)));
            txtCommonBoundary.setText(String.format("0x%04X", settings.getInt("commonBoundary", 0)));
        } catch (NumberFormatException e) {
            dialogs.showError("Invalid number format while loading settings: ", "Loa");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JPanel jPanel1 = new javax.swing.JPanel();
        javax.swing.JScrollPane jScrollPane1 = new javax.swing.JScrollPane();
        tblROM = new javax.swing.JTable();
        JButton btnAddRange = new JButton();
        JButton btnRemoveRange = new JButton();
        chkApplyROMatStartup = new javax.swing.JCheckBox();
        javax.swing.JPanel jPanel3 = new javax.swing.JPanel();
        javax.swing.JLabel jLabel6 = new javax.swing.JLabel();
        txtBanksCount = new javax.swing.JTextField();
        javax.swing.JLabel jLabel7 = new javax.swing.JLabel();
        txtCommonBoundary = new javax.swing.JTextField();
        javax.swing.JSeparator jSeparator2 = new javax.swing.JSeparator();
        javax.swing.JLabel jLabel8 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel9 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel10 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel1 = new javax.swing.JLabel();
        javax.swing.JPanel jPanel2 = new javax.swing.JPanel();
        JScrollPane jScrollPane2 = new JScrollPane();
        tblImages = new javax.swing.JTable();
        // Variables declaration - do not modify//GEN-BEGIN:variables
        JButton btnAddImage = new JButton();
        JButton btnRemoveImage = new JButton();
        JButton btnLoadNow = new JButton();
        JButton btnOK = new JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Memory Settings");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("ROM areas"));

        tblROM.setModel(new javax.swing.table.DefaultTableModel(
            new Object[][]{

            },
            new String[]{
                "From (hex)", "To (hex)"
            }
        ) {
            Class[] types = new Class[]{
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean[]{
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        tblROM.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(tblROM);

        btnAddRange.setFont(btnAddRange.getFont().deriveFont(btnAddRange.getFont().getStyle() & ~java.awt.Font.BOLD));
        btnAddRange.setText("Add");
        btnAddRange.addActionListener(this::btnAddRangeActionPerformed);

        btnRemoveRange.setFont(btnRemoveRange.getFont().deriveFont(btnRemoveRange.getFont().getStyle() & ~java.awt.Font.BOLD));
        btnRemoveRange.setText("Remove");
        btnRemoveRange.addActionListener(this::btnRemoveRangeActionPerformed);

        chkApplyROMatStartup.setFont(chkApplyROMatStartup.getFont().deriveFont(chkApplyROMatStartup.getFont().getStyle() & ~java.awt.Font.BOLD));
        chkApplyROMatStartup.setText("Apply at startup");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(chkApplyROMatStartup)
                            .addGap(0, 0, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGap(0, 0, Short.MAX_VALUE)
                            .addComponent(btnRemoveRange)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnAddRange))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnAddRange)
                        .addComponent(btnRemoveRange))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(chkApplyROMatStartup)
                    .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Bank-switching"));

        jLabel6.setFont(jLabel6.getFont().deriveFont(jLabel6.getFont().getStyle() & ~java.awt.Font.BOLD));
        jLabel6.setText("Banks count:");

        txtBanksCount.setText("0");

        jLabel7.setFont(jLabel7.getFont().deriveFont(jLabel7.getFont().getStyle() & ~java.awt.Font.BOLD));
        jLabel7.setText("Common boundary:");

        txtCommonBoundary.setText("0x0000");

        jLabel8.setFont(jLabel8.getFont().deriveFont(jLabel8.getFont().getStyle() & ~java.awt.Font.BOLD));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("<html>Memory banks are different locations of memory wired in a way they share the addresses. Common area is shared across all banks. ");
        jLabel8.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel9.setFont(jLabel9.getFont().deriveFont(jLabel9.getFont().getStyle() & ~java.awt.Font.BOLD));
        jLabel9.setText("<html>Banks are accessible from <strong>[0..Common]</strong>.");

        jLabel10.setFont(jLabel10.getFont().deriveFont(jLabel10.getFont().getStyle() & ~java.awt.Font.BOLD));
        jLabel10.setText("<html>Common area starts from <strong>[Common..memory end]</strong>.");

        jLabel1.setFont(jLabel1.getFont().deriveFont(jLabel1.getFont().getStyle() & ~java.awt.Font.BOLD));
        jLabel1.setText("<html><strong>NOTE:</strong> Changes will be visible after restart.");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel7))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtBanksCount)
                                        .addComponent(txtCommonBoundary))))
                            .addContainerGap())
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(txtBanksCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(txtCommonBoundary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Files to load at startup"));

        tblImages.setModel(new javax.swing.table.DefaultTableModel(
            new Object[][]{

            },
            new String[]{
                "File name", "Address", "Bank"
            }
        ) {
            Class[] types = new Class[]{
                String.class, String.class, Integer.class
            };
            boolean[] canEdit = new boolean[]{
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        tblImages.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(tblImages);

        btnAddImage.setFont(btnAddImage.getFont().deriveFont(btnAddImage.getFont().getStyle() & ~java.awt.Font.BOLD));
        btnAddImage.setText("Add");
        btnAddImage.addActionListener(this::btnAddImageActionPerformed);

        btnRemoveImage.setFont(btnRemoveImage.getFont().deriveFont(btnRemoveImage.getFont().getStyle() & ~java.awt.Font.BOLD));
        btnRemoveImage.setText("Remove");
        btnRemoveImage.addActionListener(this::btnRemoveImageActionPerformed);

        btnLoadNow.setFont(btnLoadNow.getFont().deriveFont(btnLoadNow.getFont().getStyle() & ~java.awt.Font.BOLD));
        btnLoadNow.setText("Load now");
        btnLoadNow.addActionListener(this::btnLoadNowActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnLoadNow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRemoveImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAddImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(btnAddImage)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnRemoveImage)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnLoadNow))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnOK.setText("OK");
        btnOK.addActionListener(this::btnOKActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(0, 0, Short.MAX_VALUE)
                            .addComponent(btnOK, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnOK)
                    .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddRangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddRangeActionPerformed
        try {
            Optional<Integer> from = dialogs.readInteger("Enter FROM address:", "Add ROM range", 0);
            Optional<Integer> to = dialogs.readInteger("Enter TO address:", "Add ROM range", 0);

            if (from.isPresent() && to.isPresent()) {
                RangeTree.Range range = new RangeTree.Range(from.get(), to.get());
                context.setReadOnly(range);

                tblROM.revalidate();
                tblROM.repaint();
                tblMem.revalidate();
                tblMem.repaint();
            }
        } catch (NumberFormatException e) {
            dialogs.showError("Invalid number format!", "Add ROM range");
        } catch (IllegalArgumentException e) {
            dialogs.showError(e.getMessage(), "Add ROM range");
        }
    }//GEN-LAST:event_btnAddRangeActionPerformed

    private void btnRemoveRangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveRangeActionPerformed
        RadixUtils radixUtils = RadixUtils.getInstance();
        int i = tblROM.getSelectedRow();

        Optional<RangeTree.Range> rangeOpt = Optional.empty();
        try {
            if (i >= 0) {
                int from = radixUtils.parseRadix((String) romModel.getValueAt(i, 0));
                int to = radixUtils.parseRadix((String) romModel.getValueAt(i, 1));
                rangeOpt = Optional.of(new RangeTree.Range(from, to));
            } else {
                Optional<Integer> from = dialogs.readInteger("Enter FROM address:", "Remove ROM range", 0);
                Optional<Integer> to = dialogs.readInteger("Enter TO address:", "Remove ROM range", 0);

                if (from.isPresent() && to.isPresent()) {
                    rangeOpt = Optional.of(new RangeTree.Range(from.get(), to.get()));
                }
            }

            rangeOpt.ifPresent(range -> {
                context.setReadWrite(range);
                tblROM.revalidate();
                tblROM.repaint();
                tblMem.revalidate();
                tblMem.repaint();
            });
        } catch (NumberFormatException e) {
            dialogs.showError("Invalid number format", "Remove ROM range");
        }
    }//GEN-LAST:event_btnRemoveRangeActionPerformed

    private int getPositiveIntegerOrThrow(String name, JTextField textField) {
        try {
            int number = RadixUtils.getInstance().parseRadix(textField.getText());
            if (number < 0) {
                throw new NumberFormatException();
            }
            return number;
        } catch (NumberFormatException e) {
            dialogs.showError(name + " has to be positive integer !");
            throw e;
        }
    }

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        try {
            int bCount = getPositiveIntegerOrThrow("Banks count", txtBanksCount);
            int bCommon = getPositiveIntegerOrThrow("Common boundary", txtCommonBoundary);
            memory.saveCoreSettings(
                bCount, bCommon, imagesModel.getImageFullNames(), imagesModel.getImageAddresses(),
                imagesModel.getImageBanks()
            );
            if (chkApplyROMatStartup.isSelected()) {
                memory.saveROMRanges();
            }
            dispose();
        } catch (NumberFormatException ignored) {
            dialogs.showError("Could not save settings: invalid number format", "Save settings");
        } catch (CannotUpdateSettingException ex) {
            LOGGER.error("Could not save memory settings", ex);
            dialogs.showError("Could not save settings. Please see log file for more details");
        }
    }//GEN-LAST:event_btnOKActionPerformed

    private void btnAddImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddImageActionPerformed
        dialogs.chooseFile(
            "Add memory image", "Add", Path.of(System.getProperty("user.dir")),
            new FileExtensionsFilter("Memory images", "hex", "bin")
        ).ifPresent(path -> {
            final int bank = (context.getBanksCount() > 1)
                ? dialogs.readInteger("Enter memory bank index:", "Add memory image", 0).orElse(0)
                : 0;

            if (!path.toString().toLowerCase().endsWith(".hex")) {
                try {
                    dialogs
                        .readInteger("Enter image address:", "Add image", 0)
                        .ifPresent(address -> imagesModel.addImage(path, address, bank));
                } catch (NumberFormatException e) {
                    dialogs.showError("Invalid number format", "Add image");
                }
            } else {
                imagesModel.addImage(path, 0, bank);
            }
        });
    }//GEN-LAST:event_btnAddImageActionPerformed

    private void btnRemoveImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveImageActionPerformed
        int index = tblImages.getSelectedRow();
        if (index == -1) {
            dialogs.showError("Image has to be selected", "Remove image");
        } else {
            Dialogs.DialogAnswer answer = dialogs.ask(
                "Are you sure to remove selected image from the list?", "Remove image"
            );
            if (answer == Dialogs.DialogAnswer.ANSWER_YES) {
                imagesModel.removeImageAt(index);
            }
        }
    }//GEN-LAST:event_btnRemoveImageActionPerformed

    private void btnLoadNowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadNowActionPerformed
        int index = tblImages.getSelectedRow();
        if (index == -1) {
            dialogs.showError("Image has to be selected", "Load image now");
        } else {
            memory.loadImage(
                Path.of(imagesModel.getFileNameAtRow(index)), imagesModel.getImageAddressAtRow(index),
                imagesModel.getImageBankAtRow(index)
            );
            tblMem.getTableModel().fireTableDataChanged();
        }
    }//GEN-LAST:event_btnLoadNowActionPerformed

    private javax.swing.JCheckBox chkApplyROMatStartup;
    private javax.swing.JTable tblImages;
    private javax.swing.JTable tblROM;
    private javax.swing.JTextField txtBanksCount;
    private javax.swing.JTextField txtCommonBoundary;
    // End of variables declaration//GEN-END:variables
}
