# Where things are
source:      .
destination: ./_site
plugins_dir: ./_plugins
layouts_dir: ./_layouts
data_dir:    ./_data

# Serving
baseurl: ""
url: http://www.net.emustudio.net/
detach:  false
port:    4000
host:    0.0.0.0

# Handling Reading
safe:         true
include:      [".htaccess", '_pages']
exclude:
  - .gitignore
  - README.md
  - build.sh
  - Gemfile
  - Gemfile.lock
  - _documentation
keep_files: [documentation, images, .git, files]
encoding:     "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Filtering Content
show_drafts: null
limit_posts: 0
future:      true
unpublished: false

# Plugins
plugins:   [jekyll-sitemap]
repository: emustudio/emuStudio

google_analytics_id: UA-3492956-5

# Conversion
markdown:    kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"

# Outputting
permalink:        pretty
timezone:      Europe/Prague

quiet:    false
defaults: []

# Markdown Processors
rdiscount:
  extensions: []

redcarpet:
  extensions: []

sass:
  style: compressed

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

  syntax_highlighter_opts:
    wrap:              div
    line_numbers:      inline
    line_number_start: 1
    tab_width:         4
    bold_every:        10
    css:               style
