source 'https://rubygems.org'

require 'json'
require 'open-uri'
versions = JSON.parse(open('https://pages.github.com/versions.json').read)

gem "jekyll", versions['3.3.0']
gem 'github-pages', versions['github-pages']
gem 'asciidoctor-diagram', versions['1.5.4']
gem 'jekyll-asciidoc', versions['2.0.1']
gem 'pygments.rb', versions['1.1.1']
