source 'https://rubygems.org'

require 'json'
require 'open-uri'
versions = JSON.parse(open('https://pages.github.com/versions.json').read)

gem 'asciidoctor', versions['1.5.5']
gem 'pygments.rb', versions['1.1.1']

group :jekyll_plugins do
  gem 'github-pages', versions['124']
  gem 'jekyll-asciidoc', versions['2.0.1']
  gem 'asciidoctor-diagram', versions['1.5.4']
  gem 'jekyll-sitemap'
end
