/*
 * This file is part of emuStudio.
 *
 * Copyright (C) 2006-2020  Peter Jakubčo
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

package net.emustudio.plugins.memory.rasp.gui;

import net.emustudio.emulib.plugins.memory.Memory;
import net.emustudio.emulib.runtime.interaction.Dialogs;
import net.emustudio.plugins.memory.rasp.RASPMemoryContextImpl;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import javax.swing.*;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.io.File;
import java.io.IOException;
import java.util.Objects;

public class MemoryWindow extends javax.swing.JFrame {
    private final static Logger LOGGER = LoggerFactory.getLogger(MemoryWindow.class);

    private final Dialogs dialogs;

    private final RASPMemoryContextImpl memory;
    private final RASPTableModel tableModel;
    private File recentOpenPath;

    public MemoryWindow(RASPMemoryContextImpl context, Dialogs dialogs) {
        this.dialogs = Objects.requireNonNull(dialogs);
        this.memory = Objects.requireNonNull(context);
        this.recentOpenPath = new File(System.getProperty("user.home"));

        initComponents();
        tableModel = new RASPTableModel(memory);
        updateTable();
        memory.addMemoryListener(new Memory.MemoryListener() {

            @Override
            public void memoryChanged(int position) {
                updateTable();
            }

            @Override
            public void memorySizeChanged() {
                updateTable();
            }
        });
    }

    private void updateTable() {
        tableModel.fireTableDataChanged();
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JScrollPane jScrollPane1 = new JScrollPane();
        memoryTable = new javax.swing.JTable();
        JToolBar jToolBar1 = new JToolBar();
        // Variables declaration - do not modify//GEN-BEGIN:variables
        JButton jButton1 = new JButton();
        JButton jButton2 = new JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("RASP Memory");

        memoryTable.setModel(new RASPTableModel(memory));
        memoryTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                memoryTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(memoryTable);
        if (memoryTable.getColumnModel().getColumnCount() > 0) {
            memoryTable.getColumnModel().getColumn(0).setResizable(false);
            memoryTable.getColumnModel().getColumn(1).setResizable(false);
        }

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/net/emustudio/plugins/memory/raspm/gui/document-open.png"))); // NOI18N
        jButton1.setFocusable(false);
        jButton1.addActionListener(this::onOpenClick);
        jToolBar1.add(jButton1);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/net/emustudio/plugins/memory/raspm/gui/edit-delete.png"))); // NOI18N
        jButton2.setFocusable(false);
        jButton2.addActionListener(this::onClearClick);
        jToolBar1.add(jButton2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 491, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void onOpenClick(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onOpenClick
        JFileChooser chooser = new JFileChooser();

        FileNameExtensionFilter binaryFileFilter = new FileNameExtensionFilter("Compiled program for RASP (*.bin)", "bin");

        chooser.setDialogTitle("Load memory with compiled program file");
        chooser.addChoosableFileFilter(binaryFileFilter);
        chooser.setFileFilter(binaryFileFilter);
        chooser.setApproveButtonText("Load");
        chooser.setCurrentDirectory(recentOpenPath);

        int chooserReturnValue = chooser.showOpenDialog(this);
        if (chooserReturnValue == JFileChooser.APPROVE_OPTION) {
            String filePath = chooser.getSelectedFile().getAbsolutePath();
            recentOpenPath = chooser.getCurrentDirectory();
            try {
                memory.loadFromFile(filePath);
                updateTable();
            } catch (IOException | ClassNotFoundException ex) {
                LOGGER.error("Could not read file: {}", filePath, ex);
                dialogs.showError("Could not open file " + filePath + ". Please see log file for details.");
            }
        }
    }//GEN-LAST:event_onOpenClick

    private void onClearClick(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onClearClick
        memory.clear();
    }//GEN-LAST:event_onClearClick

    /**
     * Called when user double-clicks at a row; editor is displayed at the
     * "Numeric value" column. It is to make UI more user friendly as user does
     * not have to click at an editable cell, he/she just double-clicks the row.
     *
     * @param evt the click event
     */
    private void memoryTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_memoryTableMouseClicked
        int row = memoryTable.rowAtPoint(evt.getPoint());
        //check if double-click
        if (evt.getClickCount() == 2) {
            memoryTable.editCellAt(row, 1);
        }
    }//GEN-LAST:event_memoryTableMouseClicked


    private javax.swing.JTable memoryTable;
    // End of variables declaration//GEN-END:variables
}
