package net.emustudio.plugins.device.zxspectrum.ula.audio;

/**
 * Minimal sink interface for the PCM stream produced by {@link Beeper}.
 *
 * <p>The beeper always writes whole PCM frames, not abstract samples. In this module a frame is
 * one left sample plus one right sample, both 16-bit signed PCM values, so
 * {@code length % Beeper.FRAME_SIZE == 0} is expected. The byte order is little-endian because
 * {@link Beeper} stores samples with {@link java.nio.ByteBuffer#putShort(short)} after switching
 * the buffer to {@link java.nio.ByteOrder#LITTLE_ENDIAN}, and {@link SoundOutputSink} opens Java
 * Sound with {@code bigEndian=false}.
 *
 * <p>{@link #flush()} means "drop queued but not yet consumed audio". That lets {@link Beeper}
 * reset the audible state without waiting for already-buffered host audio to drain. The
 * {@link #close()} contract is the usual terminal one: after close, no more writes are expected.
 *
 * <p>References:
 * <ul>
 * <li><a href="https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/nio/ByteBuffer.html">Oracle:
 * ByteBuffer</a></li>
 * <li><a href="https://docs.oracle.com/javase/9/docs/api/javax/sound/sampled/AudioFormat.html">Oracle:
 * AudioFormat</a></li>
 * <li><a href="https://docs.oracle.com/en/java/javase/11/docs/api/java.desktop/javax/sound/sampled/SourceDataLine.html">Oracle:
 * SourceDataLine</a></li>
 * </ul>
 */
public interface AudioSink extends AutoCloseable {
    /**
     * Sink that silently discards all PCM frames while preserving the same call pattern as a real
     * output sink.
     */
    AudioSink NULL = (samples, length) -> {
    };

    /**
     * Accepts {@code length} valid bytes from {@code samples}.
     *
     * <p>The bytes represent whole PCM frames generated by {@link Beeper}.
     */
    void write(byte[] samples, int length);

    default void flush() {
    }

    @Override
    default void close() {
    }
}
