/* SPDX-FileCopyrightText: 2006-2026 Peter Jakubčo
   SPDX-License-Identifier: GPL-3.0-or-later */
package net.emustudio.plugins.device.zxspectrum.ula.audio;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import javax.sound.sampled.LineUnavailableException;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

import static net.emustudio.plugins.device.zxspectrum.bus.api.ZxParameters.ZX_48K_CPU_FREQUENCY;
import static net.emustudio.plugins.device.zxspectrum.ula.Constants.AUDIO_DEFAULT_BATCH_FRAMES;

/**
 * Resamples the ZX Spectrum's EAR/MIC output line into host PCM audio.
 *
 * <p>The ULA exposes two output bits on port {@code 0xFE}: EAR/internal speaker on bit 4 and MIC
 * on bit 3 (active low). On real 48K hardware these are not independent digital channels; they
 * share the same analog node through resistors and therefore produce four observable voltage levels.
 * This class uses the Issue 3 levels from the hardware reference and converts them into signed PCM
 * amplitudes. That preserves the important property that MIC changes the loudness slightly, but it
 * does not invert the waveform or create a separate square wave.
 *
 * <p>The math is fixed-point time accumulation:
 * <pre>
 * accumulator += passedCycles * sampleRate
 * samplesToGenerate = accumulator / cpuFrequency
 * accumulator %= cpuFrequency
 * </pre>
 * {@code cpuFrequency} is the ZX Spectrum clock in T-states per second and {@code sampleRate} is
 * the host audio rate in frames per second. The ratio is not integral
 * ({@code 3_500_000 / 48_000 ~= 72.9167}), so most calls end in the middle of a host sample.
 * Carrying the remainder in {@code sampleTickRemainder} preserves long-term timing and avoids
 * drift.
 *
 * <p>Each generated frame writes the same signed 16-bit amplitude to left and right channels. The
 * amplitudes are derived once from the Issue 3 voltage table by centering the analog range around
 * its midpoint and scaling it into 16-bit PCM. The backing {@link ByteBuffer} is little-endian to
 * match the Java Sound format created by {@link SoundAudioSink}.
 *
 * <p>References:
 * <ul>
 * <li><a href="https://worldofspectrum.org/faq/reference/48kreference.htm">World of Spectrum:
 * 48K ZX Spectrum Technical Information</a></li>
 * <li><a href="https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/nio/ByteBuffer.html">Oracle:
 * ByteBuffer</a></li>
 * <li><a href="https://docs.oracle.com/javase/9/docs/api/javax/sound/sampled/AudioFormat.html">Oracle:
 * AudioFormat</a></li>
 * </ul>
 */
public class Beeper implements AutoCloseable {
    private static final Logger LOGGER = LoggerFactory.getLogger(Beeper.class);

    // Average output sample period at 48 kHz = 3,500,000 / 48,000 ≈ 72.9 CPU cycles per sample
    public static final int DEFAULT_SAMPLE_RATE = 48_000;

    private static final int DEFAULT_VOLUME = 100;

    public static final int CHANNELS = 2;
    public static final int BYTES_PER_SAMPLE = 2;
    public static final int FRAME_SIZE = CHANNELS * BYTES_PER_SAMPLE;

    // Peak PCM amplitude used when mapping hardware voltages to 16-bit signed samples.
    // Set to 70% of Short.MAX_VALUE to leave headroom and avoid harsh clipping distortion.
    private static final int MAX_SAMPLE_AMPLITUDE = (int) (Short.MAX_VALUE * 0.70);

    private static final short[] ISSUE_3_PCM_LEVELS = createIssue3PcmLevels();

    private final TeeAudioSink sink;
    private final int sampleRate;
    private final ByteBuffer sampleBuffer;

    private short currentSampleValue;
    private short rawSampleValue;
    private boolean audioStarted;
    private volatile int volumePercent = DEFAULT_VOLUME;
    // Carries the fractional part of cycles -> samples conversion between calls.
    private long sampleTickRemainder;

    public static Beeper createDefault() {
        try {
            return new Beeper(new SoundAudioSink(DEFAULT_SAMPLE_RATE), DEFAULT_SAMPLE_RATE);
        } catch (LineUnavailableException | IllegalArgumentException e) {
            LOGGER.warn("ZX Spectrum tone output is unavailable; continuing without sound", e);
            return silent();
        }
    }

    public static Beeper silent() {
        return new Beeper(AudioSink.NULL, DEFAULT_SAMPLE_RATE);
    }

    public Beeper(AudioSink sink, int sampleRate) {
        if (sampleRate <= 0) {
            throw new IllegalArgumentException("Sample rate must be > 0");
        }
        this.sink = new TeeAudioSink(sink);
        this.sampleRate = sampleRate;
        this.sampleBuffer = ByteBuffer.allocate(AUDIO_DEFAULT_BATCH_FRAMES * FRAME_SIZE).order(ByteOrder.LITTLE_ENDIAN);
    }

    /**
     * Sets the current EAR/MIC output state from port {@code 0xFE}.
     *
     * <p>{@code earOn} corresponds to bit 4, {@code micOn} corresponds to active-low bit 3. The
     * next PCM frames generated by {@link #passedCycles(long)} will use the mapped Issue 3 output
     * level until it changes again.
     *
     * @param earOn true if EAR bit is on (bit 4 = 1), false if off (bit 4 = 0)
     * @param micOn true if MIC bit is on (bit 3 = 0), false if off (bit 3 = 1)
     */
    public void setLevel(boolean earOn, boolean micOn) {
        audioStarted |= earOn || micOn;
        int index = (earOn ? 2 : 0) | (micOn ? 1 : 0);
        rawSampleValue = audioStarted ? ISSUE_3_PCM_LEVELS[index] : 0;
        currentSampleValue = scaleSample(rawSampleValue);
    }

    public int getSampleRate() {
        return sampleRate;
    }

    public int getVolumePercent() {
        return volumePercent;
    }

    public void setVolumePercent(int volumePercent) {
        this.volumePercent = Math.max(0, Math.min(100, volumePercent));
        currentSampleValue = scaleSample(rawSampleValue);
    }

    public void setRecordingSink(AudioSink recordingSink) {
        sink.setSecondarySink(recordingSink);
    }

    /**
     * Converts elapsed CPU T-states into host PCM frames.
     *
     * <p>This method does not emit one audio frame per call. It emits
     * {@code floor((remainder + cycles * sampleRate) / cpuFrequency)} frames, then carries the
     * leftover fractional part into the next call.
     */
    public void passedCycles(long cycles) {
        if (cycles <= 0) {
            return;
        }

        sampleTickRemainder += cycles * sampleRate;
        long samplesToGenerate = sampleTickRemainder / ZX_48K_CPU_FREQUENCY;
        sampleTickRemainder %= ZX_48K_CPU_FREQUENCY;

        for (long i = 0; i < samplesToGenerate; i++) {
            writeSample(currentSampleValue);
        }
    }

    /**
     * Drops buffered PCM data and returns the beeper to a silent low level.
     */
    public void reset() {
        rawSampleValue = 0;
        currentSampleValue = 0;
        audioStarted = false;
        sampleTickRemainder = 0;
        sampleBuffer.clear();
        sink.flushAudio();
    }

    @Override
    public void close() {
        flushSamples();
        sink.close();
    }

    private void writeSample(short sampleValue) {
        sampleBuffer.putShort(sampleValue);
        sampleBuffer.putShort(sampleValue);
        if (!sampleBuffer.hasRemaining()) {
            flushSamples();
        }
    }

    private void flushSamples() {
        int length = sampleBuffer.position();
        if (length == 0) {
            return;
        }
        sink.accept(sampleBuffer.array(), length);
        sampleBuffer.clear();
    }

    private short scaleSample(short sampleValue) {
        return (short) ((sampleValue * volumePercent) / 100);
    }

    private static short[] createIssue3PcmLevels() {
        // https://worldofspectrum.org/faq/reference/48kreference.htm

        // Bit   7   6   5   4   3   2   1   0
        //     +-------------------------------+
        //     |   |   |   | E | M |   Border  |
        //     +-------------------------------+
        //
        // - 0 in bit 3 (M) activates microphone (MIC)
        // - 1 in bit 4 (E) activates internal speaker (EAR)

        // bit: 4  3  E M  |  Iss 2  Iss 3   Iss 2 V    Iss 3 V
        //      0  1  F F  |    1      0       0.73       0.66
        //      0  0  F T  |    0      0       0.39       0.34
        //      1  1  T F  |    1      1       3.79       3.70
        //      1  0  T T  |    1      1       3.66       3.56
        double issue3_ear_F_mic_F_voltage = 0.66;
        double issue3_ear_F_mic_T_voltage = 0.34;
        double issue3_ear_T_mic_F_voltage = 3.70;
        double issue3_ear_T_mic_T_voltage = 3.56;

        double[] voltages = {
                issue3_ear_F_mic_F_voltage,
                issue3_ear_F_mic_T_voltage,
                issue3_ear_T_mic_F_voltage,
                issue3_ear_T_mic_T_voltage,
        };

        // Map [minVoltage .. maxVoltage] linearly to [-MAX_SAMPLE_AMPLITUDE .. +MAX_SAMPLE_AMPLITUDE].
        double center = (issue3_ear_F_mic_T_voltage + issue3_ear_T_mic_F_voltage) / 2.0;
        double halfRange = (issue3_ear_T_mic_F_voltage - issue3_ear_F_mic_T_voltage) / 2.0;

        short[] levels = new short[voltages.length];
        for (int i = 0; i < voltages.length; i++) {
            double normalized = (voltages[i] - center) / halfRange; // maps to [-1 .. +1]
            levels[i] = (short) Math.round(normalized * MAX_SAMPLE_AMPLITUDE);
        }
        return levels;
    }
}
