/* SPDX-FileCopyrightText: 2006-2026 Peter Jakubčo
   SPDX-License-Identifier: GPL-3.0-or-later */
package net.emustudio.plugins.device.zxspectrum.ula.audio;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import javax.sound.sampled.LineUnavailableException;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

/**
 * Resamples the ZX Spectrum's one-bit EAR/MIC output line into host PCM audio.
 *
 * <p>The ULA already decides whether the speaker line is logically high or low when software
 * writes to port {@code 0xFE}. According to the 48K hardware reference, bit 3 drives MIC when it
 * is zero and bit 4 drives EAR/internal speaker when it is one; because the lines are coupled by
 * resistors, either output affects the audible signal. This class therefore does not try to infer
 * frequency or synthesize a sine wave. It only converts a stream of "speaker is high/low for N
 * T-states" events into fixed-rate PCM frames.
 *
 * <p>The math is fixed-point time accumulation:
 * <pre>
 * accumulator += passedCycles * sampleRate
 * samplesToGenerate = accumulator / cpuFrequency
 * accumulator %= cpuFrequency
 * </pre>
 * {@code cpuFrequency} is the ZX Spectrum clock in T-states per second and {@code sampleRate} is
 * the host audio rate in frames per second. The ratio is not integral
 * ({@code 3_500_000 / 48_000 ~= 72.9167}), so most calls end in the middle of a host sample.
 * Carrying the remainder in {@code sampleTickRemainder} preserves long-term timing and avoids
 * drift.
 *
 * <p>Each generated frame writes the same signed 16-bit amplitude to left and right channels.
 * The backing {@link ByteBuffer} is little-endian to match the Java Sound format created by
 * {@link SoundOutputSink}.
 *
 * <p>References:
 * <ul>
 * <li><a href="https://worldofspectrum.org/faq/reference/48kreference.htm">World of Spectrum:
 * 48K ZX Spectrum Technical Information</a></li>
 * <li><a href="https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/nio/ByteBuffer.html">Oracle:
 * ByteBuffer</a></li>
 * <li><a href="https://docs.oracle.com/javase/9/docs/api/javax/sound/sampled/AudioFormat.html">Oracle:
 * AudioFormat</a></li>
 * </ul>
 */
public class Beeper implements AutoCloseable {
    private static final Logger LOGGER = LoggerFactory.getLogger(Beeper.class);

    static final int ZX_SPECTRUM_FREQUENCY = 3_500_000;
    static final int DEFAULT_SAMPLE_RATE = 48_000;
    private static final int DEFAULT_BATCH_FRAMES = 512;

    public static final int CHANNELS = 2;
    private static final int BYTES_PER_SAMPLE = 2;
    public static final int FRAME_SIZE = CHANNELS * BYTES_PER_SAMPLE;
    private static final short HIGH_SAMPLE = (short) (Short.MAX_VALUE * 0.35);

    private final AudioSink sink;
    private final int cpuFrequency;
    private final int sampleRate;
    private final ByteBuffer sampleBuffer;

    private boolean levelHigh;
    // Carries the fractional part of cycles -> samples conversion between calls.
    private long sampleTickRemainder;

    public static Beeper createDefault() {
        try {
            return new Beeper(
                    new SoundOutputSink(DEFAULT_SAMPLE_RATE, DEFAULT_BATCH_FRAMES),
                    ZX_SPECTRUM_FREQUENCY, DEFAULT_SAMPLE_RATE, DEFAULT_BATCH_FRAMES);
        } catch (LineUnavailableException | IllegalArgumentException e) {
            LOGGER.warn("ZX Spectrum tone output is unavailable; continuing without sound", e);
            return silent();
        }
    }

    public static Beeper silent() {
        return new Beeper(AudioSink.NULL, ZX_SPECTRUM_FREQUENCY, DEFAULT_SAMPLE_RATE, DEFAULT_BATCH_FRAMES);
    }

    public Beeper(AudioSink sink, int cpuFrequency, int sampleRate, int batchFrames) {
        if (cpuFrequency <= 0) {
            throw new IllegalArgumentException("CPU frequency must be > 0");
        }
        if (sampleRate <= 0) {
            throw new IllegalArgumentException("Sample rate must be > 0");
        }
        this.sink = sink;
        this.cpuFrequency = cpuFrequency;
        this.sampleRate = sampleRate;
        this.sampleBuffer = ByteBuffer.allocate(batchFrames * FRAME_SIZE).order(ByteOrder.LITTLE_ENDIAN);
    }

    /**
     * Sets the logical state of the Spectrum beeper line.
     *
     * <p>The next PCM frames generated by {@link #passedCycles(long)} will use this level until it
     * changes again.
     */
    public void setLevel(boolean levelHigh) {
        this.levelHigh = levelHigh;
    }

    /**
     * Converts elapsed CPU T-states into host PCM frames.
     *
     * <p>This method does not emit one audio frame per call. It emits
     * {@code floor((remainder + cycles * sampleRate) / cpuFrequency)} frames, then carries the
     * leftover fractional part into the next call.
     */
    public void passedCycles(long cycles) {
        if (cycles <= 0) {
            return;
        }

        sampleTickRemainder += cycles * sampleRate;
        long samplesToGenerate = sampleTickRemainder / cpuFrequency;
        sampleTickRemainder %= cpuFrequency;

        short sampleValue = levelHigh ? HIGH_SAMPLE : 0;
        for (long i = 0; i < samplesToGenerate; i++) {
            writeSample(sampleValue);
        }
    }

    /**
     * Drops buffered PCM data and returns the beeper to a silent low level.
     */
    public void reset() {
        levelHigh = false;
        sampleTickRemainder = 0;
        sampleBuffer.clear();
        sink.flush();
    }

    @Override
    public void close() {
        flushSamples();
        sink.close();
    }

    private void writeSample(short sampleValue) {
        sampleBuffer.putShort(sampleValue);
        sampleBuffer.putShort(sampleValue);
        if (!sampleBuffer.hasRemaining()) {
            flushSamples();
        }
    }

    private void flushSamples() {
        int length = sampleBuffer.position();
        if (length == 0) {
            return;
        }
        sink.write(sampleBuffer.array(), length);
        sampleBuffer.clear();
    }
}
